CREATE TABLE investment_loan_servicing_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_application_id BIGINT NOT NULL,
    loan_number VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    maturity_date DATE,
    last_reschedule_request_id UUID,
    schedule_changed_at TIMESTAMPTZ,
    settled_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_investment_loan_servicing_application UNIQUE (loan_application_id),
    CONSTRAINT ck_investment_loan_servicing_status CHECK (status IN ('ACTIVE','SETTLED'))
);

CREATE INDEX idx_investment_loan_servicing_status
    ON investment_loan_servicing_states (status, updated_at, id);
