-- Public application reference và exact terms snapshot cho listing nhận từ Loan.
ALTER TABLE market_listings
    ALTER COLUMN contract_number DROP NOT NULL,
    ADD COLUMN application_number VARCHAR(30),
    ADD COLUMN listing_version INTEGER,
    ADD COLUMN terms_version VARCHAR(50),
    ADD COLUMN terms_hash VARCHAR(64),
    ADD COLUMN allocation_version BIGINT,
    ADD COLUMN allocation_hash VARCHAR(64);

-- Dữ liệu V1 là fixture trước tích hợp; gắn reference rõ là legacy để Flyway nâng cấp được.
UPDATE market_listings
SET application_number = 'LEGACY-' || loan_id,
    listing_version = 1,
    terms_version = 'LEGACY-DEMO',
    terms_hash = repeat('0', 64)
WHERE application_number IS NULL;

UPDATE market_listings
SET allocation_version = 1,
    allocation_hash = repeat('0', 64)
WHERE status = 'FULLY_FUNDED' AND allocation_version IS NULL;

ALTER TABLE market_listings
    ALTER COLUMN application_number SET NOT NULL,
    ALTER COLUMN listing_version SET NOT NULL,
    ALTER COLUMN terms_version SET NOT NULL,
    ALTER COLUMN terms_hash SET NOT NULL,
    ADD CONSTRAINT ck_market_listings_listing_version CHECK (listing_version > 0),
    ADD CONSTRAINT ck_market_listings_rate_percent
        CHECK (annual_interest_rate > 0 AND annual_interest_rate <= 20.0000),
    ADD CONSTRAINT ck_market_listings_allocation_complete
        CHECK (
            status <> 'FULLY_FUNDED'
            OR (allocation_version > 0 AND allocation_hash IS NOT NULL AND fully_funded_at IS NOT NULL)
        );

CREATE UNIQUE INDEX uq_market_listings_application_round
    ON market_listings (application_number, funding_round);

-- Consumer inbox: cùng event Kafka chỉ được áp dụng một lần dù broker giao lại sau restart.
CREATE TABLE investment_processed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_version INTEGER NOT NULL,
    source VARCHAR(50) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_investment_processed_events_event_id UNIQUE (event_id)
);

CREATE INDEX idx_investment_processed_events_source_aggregate
    ON investment_processed_events (source, aggregate_id, processed_at DESC);

-- Transactional outbox cho Investment → Loan. Payload chỉ mang ID/hash/allocation tối thiểu.
CREATE TABLE investment_outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_version INTEGER NOT NULL,
    payload_json JSONB NOT NULL,
    status VARCHAR(30) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL,
    processing_started_at TIMESTAMPTZ,
    processing_token UUID,
    published_at TIMESTAMPTZ,
    last_error_code VARCHAR(50),
    last_error_detail VARCHAR(500),
    trace_id VARCHAR(100) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_investment_outbox_events_event_id UNIQUE (event_id),
    CONSTRAINT ck_investment_outbox_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'PUBLISHED', 'DEAD_LETTER')),
    CONSTRAINT ck_investment_outbox_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT ck_investment_outbox_processing_claim
        CHECK (
            (status = 'PROCESSING' AND processing_started_at IS NOT NULL AND processing_token IS NOT NULL)
            OR status <> 'PROCESSING'
        )
);

CREATE INDEX idx_investment_outbox_events_due
    ON investment_outbox_events (available_at, id)
    WHERE status IN ('PENDING', 'PROCESSING');

CREATE INDEX idx_investment_outbox_events_aggregate
    ON investment_outbox_events (aggregate_type, aggregate_id, created_at, id);
