-- Database Neon hiện hữu được baseline tại version 3 nên không chạy V3 trong source.
-- Migration tương thích này bảo đảm cả database baseline cũ và database tạo mới đều
-- có cùng schema cho Loan ↔ Investment events. Mọi thao tác đều idempotent về cấu trúc.
ALTER TABLE market_listings
    ALTER COLUMN contract_number DROP NOT NULL,
    ADD COLUMN IF NOT EXISTS application_number VARCHAR(30),
    ADD COLUMN IF NOT EXISTS listing_version INTEGER,
    ADD COLUMN IF NOT EXISTS terms_version VARCHAR(50),
    ADD COLUMN IF NOT EXISTS terms_hash VARCHAR(64),
    ADD COLUMN IF NOT EXISTS allocation_version BIGINT,
    ADD COLUMN IF NOT EXISTS allocation_hash VARCHAR(64);

UPDATE market_listings
SET application_number = 'LEGACY-' || loan_id,
    listing_version = COALESCE(listing_version, 1),
    terms_version = COALESCE(terms_version, 'LEGACY-DEMO'),
    terms_hash = COALESCE(terms_hash, repeat('0', 64))
WHERE application_number IS NULL
   OR listing_version IS NULL
   OR terms_version IS NULL
   OR terms_hash IS NULL;

UPDATE market_listings
SET allocation_version = COALESCE(allocation_version, 1),
    allocation_hash = COALESCE(allocation_hash, repeat('0', 64))
WHERE status = 'FULLY_FUNDED'
  AND (allocation_version IS NULL OR allocation_hash IS NULL);

ALTER TABLE market_listings
    ALTER COLUMN application_number SET NOT NULL,
    ALTER COLUMN listing_version SET NOT NULL,
    ALTER COLUMN listing_version SET DEFAULT 1,
    ALTER COLUMN terms_version SET NOT NULL,
    ALTER COLUMN terms_hash SET NOT NULL,
    ALTER COLUMN credit_score DROP NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_market_listings_listing_version') THEN
        ALTER TABLE market_listings
            ADD CONSTRAINT ck_market_listings_listing_version CHECK (listing_version > 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_market_listings_rate_percent') THEN
        ALTER TABLE market_listings
            ADD CONSTRAINT ck_market_listings_rate_percent
                CHECK (annual_interest_rate > 0 AND annual_interest_rate <= 20.0000);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_market_listings_allocation_complete') THEN
        ALTER TABLE market_listings
            ADD CONSTRAINT ck_market_listings_allocation_complete
                CHECK (
                    status <> 'FULLY_FUNDED'
                    OR (allocation_version > 0 AND allocation_hash IS NOT NULL AND fully_funded_at IS NOT NULL)
                );
    END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS uq_market_listings_application_round
    ON market_listings (application_number, funding_round);

CREATE TABLE IF NOT EXISTS investment_processed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_version INTEGER NOT NULL,
    source VARCHAR(50) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_investment_processed_events_event_id UNIQUE (event_id)
);

-- Một số database demo đã có inbox legacy chỉ gồm event_id/event_type/processed_at.
-- Nâng cấp tại chỗ để giữ lịch sử idempotency thay vì drop/recreate bảng.
ALTER TABLE investment_processed_events
    ADD COLUMN IF NOT EXISTS id BIGINT,
    ADD COLUMN IF NOT EXISTS event_version INTEGER,
    ADD COLUMN IF NOT EXISTS source VARCHAR(50),
    ADD COLUMN IF NOT EXISTS aggregate_id VARCHAR(100),
    ADD COLUMN IF NOT EXISTS received_at TIMESTAMPTZ;

DO $$
DECLARE
    max_id BIGINT;
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'investment_processed_events'
          AND column_name = 'event_id'
          AND udt_name <> 'uuid'
    ) THEN
        ALTER TABLE investment_processed_events
            ALTER COLUMN event_id TYPE UUID USING event_id::uuid;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'investment_processed_events'
          AND column_name = 'id'
          AND column_default IS NULL
          AND is_identity = 'NO'  -- Bỏ qua identity column (database mới); chỉ patch bảng legacy
    ) THEN
        CREATE SEQUENCE IF NOT EXISTS investment_processed_events_id_compat_seq;
        ALTER SEQUENCE investment_processed_events_id_compat_seq
            OWNED BY investment_processed_events.id;
        ALTER TABLE investment_processed_events
            ALTER COLUMN id SET DEFAULT nextval('investment_processed_events_id_compat_seq');
    END IF;

    UPDATE investment_processed_events
    SET id = nextval(pg_get_serial_sequence('investment_processed_events', 'id'))
    WHERE id IS NULL;

    SELECT MAX(id) INTO max_id FROM investment_processed_events;
    IF max_id IS NOT NULL THEN
        PERFORM setval(pg_get_serial_sequence('investment_processed_events', 'id'), max_id, true);
    END IF;
END
$$;

UPDATE investment_processed_events
SET event_version = COALESCE(event_version, 1),
    source = COALESCE(source, 'LEGACY'),
    aggregate_id = COALESCE(aggregate_id, event_id::text),
    received_at = COALESCE(received_at, processed_at);

ALTER TABLE investment_processed_events
    ALTER COLUMN id SET NOT NULL,
    ALTER COLUMN event_version SET NOT NULL,
    ALTER COLUMN source SET NOT NULL,
    ALTER COLUMN aggregate_id SET NOT NULL,
    ALTER COLUMN received_at SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_investment_processed_events_id_compat
    ON investment_processed_events (id);

CREATE INDEX IF NOT EXISTS idx_investment_processed_events_source_aggregate
    ON investment_processed_events (source, aggregate_id, processed_at DESC);

CREATE TABLE IF NOT EXISTS investment_outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_version INTEGER NOT NULL,
    payload_json JSONB NOT NULL,
    status VARCHAR(30) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL,
    processing_started_at TIMESTAMPTZ,
    processing_token UUID,
    published_at TIMESTAMPTZ,
    last_error_code VARCHAR(50),
    last_error_detail VARCHAR(500),
    trace_id VARCHAR(100) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_investment_outbox_events_event_id UNIQUE (event_id),
    CONSTRAINT ck_investment_outbox_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'PUBLISHED', 'DEAD_LETTER')),
    CONSTRAINT ck_investment_outbox_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT ck_investment_outbox_processing_claim
        CHECK (
            (status = 'PROCESSING' AND processing_started_at IS NOT NULL AND processing_token IS NOT NULL)
            OR status <> 'PROCESSING'
        )
);

-- Outbox legacy dùng payload/schema_version/occurred_at. Thêm schema relay mới,
-- copy dữ liệu tương ứng rồi hạ NOT NULL của cột legacy để entity mới insert được.
ALTER TABLE investment_outbox_events
    ADD COLUMN IF NOT EXISTS event_version INTEGER,
    ADD COLUMN IF NOT EXISTS payload_json JSONB,
    ADD COLUMN IF NOT EXISTS available_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS processing_started_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS processing_token UUID,
    ADD COLUMN IF NOT EXISTS last_error_code VARCHAR(50),
    ADD COLUMN IF NOT EXISTS last_error_detail VARCHAR(500),
    ADD COLUMN IF NOT EXISTS trace_id VARCHAR(100),
    ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

DO $$
DECLARE
    max_id BIGINT;
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'investment_outbox_events'
          AND column_name = 'event_id'
          AND udt_name <> 'uuid'
    ) THEN
        ALTER TABLE investment_outbox_events
            ALTER COLUMN event_id TYPE UUID USING event_id::uuid;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'investment_outbox_events'
          AND column_name = 'id'
          AND column_default IS NULL
          AND is_identity = 'NO'  -- Bỏ qua identity column (database mới); chỉ patch bảng legacy
    ) THEN
        CREATE SEQUENCE IF NOT EXISTS investment_outbox_events_id_compat_seq;
        ALTER SEQUENCE investment_outbox_events_id_compat_seq
            OWNED BY investment_outbox_events.id;
        ALTER TABLE investment_outbox_events
            ALTER COLUMN id SET DEFAULT nextval('investment_outbox_events_id_compat_seq');
    END IF;

    SELECT MAX(id) INTO max_id FROM investment_outbox_events;
    IF max_id IS NOT NULL THEN
        PERFORM setval(pg_get_serial_sequence('investment_outbox_events', 'id'), max_id, true);
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'investment_outbox_events'
          AND column_name = 'schema_version'
    ) THEN
        EXECUTE $sql$
            UPDATE investment_outbox_events
            SET event_version = COALESCE(
                event_version,
                CASE
                    WHEN schema_version ~ '^[1-9][0-9]*$' THEN schema_version::integer
                    ELSE 1
                END
            )
        $sql$;
    ELSE
        UPDATE investment_outbox_events
        SET event_version = 1
        WHERE event_version IS NULL;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'investment_outbox_events'
          AND column_name = 'payload'
    ) THEN
        EXECUTE $sql$
            UPDATE investment_outbox_events
            SET payload_json = payload::jsonb
            WHERE payload_json IS NULL
        $sql$;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'investment_outbox_events'
          AND column_name = 'occurred_at'
    ) THEN
        EXECUTE $sql$
            UPDATE investment_outbox_events
            SET available_at = COALESCE(available_at, occurred_at, created_at)
            WHERE available_at IS NULL
        $sql$;
    ELSE
        UPDATE investment_outbox_events
        SET available_at = created_at
        WHERE available_at IS NULL;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'investment_outbox_events'
          AND column_name = 'last_error'
    ) THEN
        EXECUTE $sql$
            UPDATE investment_outbox_events
            SET last_error_code = CASE
                    WHEN last_error IS NOT NULL AND last_error_code IS NULL THEN 'LEGACY_ERROR'
                    ELSE last_error_code
                END,
                last_error_detail = COALESCE(last_error_detail, left(last_error, 500))
        $sql$;
    END IF;

    -- Cột legacy phải nullable vì code mới không còn ghi các trường này.
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'investment_outbox_events'
          AND column_name = 'topic'
    ) THEN
        ALTER TABLE investment_outbox_events ALTER COLUMN topic DROP NOT NULL;
    END IF;
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'investment_outbox_events'
          AND column_name = 'partition_key'
    ) THEN
        ALTER TABLE investment_outbox_events ALTER COLUMN partition_key DROP NOT NULL;
    END IF;
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'investment_outbox_events'
          AND column_name = 'payload'
    ) THEN
        ALTER TABLE investment_outbox_events ALTER COLUMN payload DROP NOT NULL;
    END IF;
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'investment_outbox_events'
          AND column_name = 'schema_version'
    ) THEN
        ALTER TABLE investment_outbox_events ALTER COLUMN schema_version DROP NOT NULL;
    END IF;
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'investment_outbox_events'
          AND column_name = 'occurred_at'
    ) THEN
        ALTER TABLE investment_outbox_events ALTER COLUMN occurred_at DROP NOT NULL;
    END IF;
END
$$;

UPDATE investment_outbox_events
SET event_version = COALESCE(event_version, 1),
    payload_json = COALESCE(payload_json, '{}'::jsonb),
    available_at = COALESCE(available_at, created_at),
    trace_id = COALESCE(trace_id, 'legacy-' || event_id::text),
    version = COALESCE(version, 0);

ALTER TABLE investment_outbox_events
    ALTER COLUMN event_version SET NOT NULL,
    ALTER COLUMN payload_json SET NOT NULL,
    ALTER COLUMN available_at SET NOT NULL,
    ALTER COLUMN trace_id SET NOT NULL,
    ALTER COLUMN version SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_investment_outbox_status') THEN
        ALTER TABLE investment_outbox_events
            ADD CONSTRAINT ck_investment_outbox_status
                CHECK (status IN ('PENDING', 'PROCESSING', 'PUBLISHED', 'DEAD_LETTER'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_investment_outbox_attempt_count') THEN
        ALTER TABLE investment_outbox_events
            ADD CONSTRAINT ck_investment_outbox_attempt_count CHECK (attempt_count >= 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_investment_outbox_processing_claim') THEN
        ALTER TABLE investment_outbox_events
            ADD CONSTRAINT ck_investment_outbox_processing_claim
                CHECK (
                    (status = 'PROCESSING' AND processing_started_at IS NOT NULL AND processing_token IS NOT NULL)
                    OR status <> 'PROCESSING'
                );
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_investment_outbox_events_due
    ON investment_outbox_events (available_at, id)
    WHERE status IN ('PENDING', 'PROCESSING');

CREATE INDEX IF NOT EXISTS idx_investment_outbox_events_aggregate
    ON investment_outbox_events (aggregate_type, aggregate_id, created_at, id);
