-- Sổ lệnh Ask/Bid cho chợ thứ cấp Notes (task INV-E2, plan INV-E2-order-book-matching).
--
-- Thay bảng tin của V2: thay vì treo từng Note với một giá cố định cho người mua chọn, nhà đầu tư
-- đặt lệnh bán (ASK) và lệnh mua (BID) có giá; hệ thống khớp liên tục theo ưu tiên giá rồi thời
-- gian. Mỗi đợt gọi vốn (market_listing) có một sổ riêng vì chỉ Note cùng đợt mới cùng mệnh giá,
-- cùng lãi suất, cùng lịch trả nợ — tức thay thế được cho nhau.
--
-- Giá đặt theo phần nghìn của dư nợ gốc còn lại (price_permille, 1..1000 = 0,1%..100%). Trần
-- 100% giữ nguyên nguyên tắc của INV-E1: người mua không bao giờ trả quá phần gốc sẽ nhận về.
-- Đặt giá theo % thay vì theo đồng để sổ không lệch khi người vay trả bớt nợ: số tiền được tính
-- lại theo dư nợ tại đúng lúc khớp.

-- Một dòng cho mỗi sổ. Dòng này là chỗ khóa (SELECT ... FOR UPDATE) khi đặt, khớp hoặc huỷ lệnh,
-- nên mọi thay đổi của cùng một sổ chạy lần lượt và kết quả khớp luôn xác định.
CREATE TABLE order_books (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id            BIGINT        NOT NULL,
    loan_id               BIGINT        NOT NULL,

    -- Bộ đếm tăng dần mỗi lần sổ thay đổi. Vừa là thứ tự thời gian của lệnh (lệnh vào sổ nhận
    -- giá trị hiện tại), vừa là số phiên bản của ảnh chụp đẩy cho client để bỏ bản cũ đến muộn.
    last_sequence         BIGINT        NOT NULL DEFAULT 0,

    -- Giá khớp gần nhất, để hiển thị; null khi sổ chưa có giao dịch nào.
    last_trade_permille   INT,
    last_trade_at         TIMESTAMPTZ,

    created_at            TIMESTAMPTZ   NOT NULL,
    updated_at            TIMESTAMPTZ   NOT NULL,

    CONSTRAINT fk_order_books_listing FOREIGN KEY (listing_id) REFERENCES market_listings (id),
    CONSTRAINT ck_order_books_sequence CHECK (last_sequence >= 0),
    CONSTRAINT ck_order_books_last_trade CHECK (last_trade_permille IS NULL
        OR (last_trade_permille BETWEEN 1 AND 1000 AND last_trade_at IS NOT NULL))
);

CREATE UNIQUE INDEX uq_order_books_listing_id ON order_books (listing_id);

-- Lệnh mua/bán. Lệnh không bị xoá: hết hiệu lực thì đổi trạng thái để còn lịch sử đối soát.
CREATE TABLE order_book_orders (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_reference       VARCHAR(50)   NOT NULL,
    order_book_id         BIGINT        NOT NULL,
    listing_id            BIGINT        NOT NULL,
    investor_id           VARCHAR(100)  NOT NULL,
    side                  VARCHAR(4)    NOT NULL,
    price_permille        INT           NOT NULL,
    quantity              INT           NOT NULL,
    filled_quantity       INT           NOT NULL DEFAULT 0,
    status                VARCHAR(20)   NOT NULL,

    -- Thứ tự thời gian trong sổ. Null khi lệnh mua còn chờ giữ tiền: chưa vào sổ thì chưa có
    -- chỗ xếp hàng, tránh để lệnh chờ mạng "giữ chỗ" trước lệnh đã sẵn sàng.
    sequence              BIGINT,

    -- Chỉ lệnh mua có. hold_amount là số tiền đã giữ lúc đặt, đủ cho mọi lần khớp vì giá khớp
    -- không cao hơn giá đặt và dư nợ chỉ giảm. hold_consumed là tổng đã khớp, phần còn lại được
    -- nhả khi lệnh kết thúc (hold_released_at).
    hold_reference        VARCHAR(100),
    hold_amount           NUMERIC(18,2),
    hold_consumed         NUMERIC(18,2) NOT NULL DEFAULT 0,
    hold_released_at      TIMESTAMPTZ,

    -- Người đặt đã xác nhận biết khoản vay đang nợ xấu (INV-E1 mục 8.2).
    acknowledged_default  BOOLEAN       NOT NULL DEFAULT FALSE,

    cancel_reason         VARCHAR(30),
    cancelled_at          TIMESTAMPTZ,
    reject_reason_code    VARCHAR(50),
    reject_reason_detail  VARCHAR(255),

    idempotency_key       VARCHAR(100)  NOT NULL,
    request_hash          VARCHAR(64)   NOT NULL,

    version               BIGINT        NOT NULL DEFAULT 0,
    created_by            VARCHAR(100)  NOT NULL,
    updated_by            VARCHAR(100)  NOT NULL,
    created_at            TIMESTAMPTZ   NOT NULL,
    updated_at            TIMESTAMPTZ   NOT NULL,

    CONSTRAINT fk_order_book_orders_book FOREIGN KEY (order_book_id) REFERENCES order_books (id),
    CONSTRAINT fk_order_book_orders_listing FOREIGN KEY (listing_id) REFERENCES market_listings (id),
    CONSTRAINT ck_order_book_orders_side CHECK (side IN ('BID', 'ASK')),
    CONSTRAINT ck_order_book_orders_status CHECK (status IN
        ('PENDING_FUNDS', 'OPEN', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED')),
    CONSTRAINT ck_order_book_orders_price CHECK (price_permille BETWEEN 1 AND 1000),
    CONSTRAINT ck_order_book_orders_quantity CHECK (quantity > 0),
    CONSTRAINT ck_order_book_orders_filled CHECK (filled_quantity BETWEEN 0 AND quantity),

    -- Trạng thái và số lượng khớp phải nói cùng một điều.
    CONSTRAINT ck_order_book_orders_fill_state CHECK (
        (status = 'FILLED') = (filled_quantity = quantity)
        AND (status <> 'PARTIALLY_FILLED' OR filled_quantity BETWEEN 1 AND quantity - 1)
        AND (status NOT IN ('PENDING_FUNDS', 'OPEN', 'REJECTED') OR filled_quantity = 0)),

    -- Lệnh đã vào sổ phải có thứ tự thời gian.
    CONSTRAINT ck_order_book_orders_sequence CHECK (
        status IN ('PENDING_FUNDS', 'REJECTED') OR sequence IS NOT NULL),

    -- Lệnh bán không giữ tiền; lệnh mua đã vào sổ thì phải có tiền giữ.
    CONSTRAINT ck_order_book_orders_hold CHECK (
        (side = 'ASK' AND hold_reference IS NULL AND hold_amount IS NULL AND hold_consumed = 0)
        OR (side = 'BID' AND hold_amount IS NOT NULL AND hold_amount > 0
            AND (status IN ('PENDING_FUNDS', 'REJECTED') OR hold_reference IS NOT NULL))),

    -- Không bao giờ chi quá số tiền đã giữ: bất biến tiền của lệnh mua.
    CONSTRAINT ck_order_book_orders_hold_consumed CHECK (
        hold_consumed >= 0 AND (hold_amount IS NULL OR hold_consumed <= hold_amount)),

    CONSTRAINT ck_order_book_orders_cancelled CHECK (
        (status = 'CANCELLED') = (cancelled_at IS NOT NULL AND cancel_reason IS NOT NULL)),
    CONSTRAINT ck_order_book_orders_rejected CHECK (
        (status = 'REJECTED') = (reject_reason_code IS NOT NULL))
);

CREATE UNIQUE INDEX uq_order_book_orders_order_reference ON order_book_orders (order_reference);

-- Gửi lại cùng Idempotency-Key trả về lệnh cũ thay vì đặt lệnh thứ hai.
CREATE UNIQUE INDEX uq_order_book_orders_investor_id_idempotency_key
    ON order_book_orders (investor_id, idempotency_key);

-- Tìm lệnh đối ứng tốt nhất khi khớp: chỉ lệnh còn hiệu lực, sắp theo giá rồi thời gian.
CREATE INDEX idx_order_book_orders_book_side_price_sequence
    ON order_book_orders (order_book_id, side, price_permille, sequence)
    WHERE status IN ('OPEN', 'PARTIALLY_FILLED');

-- "Lệnh của tôi", mới nhất trước.
CREATE INDEX idx_order_book_orders_investor_id_created_at
    ON order_book_orders (investor_id, created_at DESC);

-- Worker nhả tiền: lệnh mua đã kết thúc mà phần tiền giữ còn lại chưa nhả.
CREATE INDEX idx_order_book_orders_release_pending
    ON order_book_orders (id)
    WHERE side = 'BID' AND status IN ('FILLED', 'CANCELLED')
      AND hold_reference IS NOT NULL AND hold_released_at IS NULL;

-- Note đang nằm trong một lệnh bán. Unique theo note_id là chốt ở tầng dữ liệu để một Note không
-- bị bán hai lần qua hai lệnh. Note vẫn thuộc người bán và vẫn nhận gốc lãi cho tới khi khớp;
-- dòng khóa bị xoá khi Note được bán hoặc lệnh bán bị huỷ.
CREATE TABLE order_book_note_locks (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id               BIGINT        NOT NULL,
    ask_order_id          BIGINT        NOT NULL,
    created_at            TIMESTAMPTZ   NOT NULL,
    updated_at            TIMESTAMPTZ   NOT NULL,

    CONSTRAINT fk_order_book_note_locks_note FOREIGN KEY (note_id) REFERENCES investment_notes (id),
    CONSTRAINT fk_order_book_note_locks_order FOREIGN KEY (ask_order_id) REFERENCES order_book_orders (id)
);

CREATE UNIQUE INDEX uq_order_book_note_locks_note_id ON order_book_note_locks (note_id);
CREATE INDEX idx_order_book_note_locks_ask_order_id ON order_book_note_locks (ask_order_id, note_id);

-- Một lần khớp giữa một lệnh mua và một lệnh bán, có thể gồm nhiều Note. Bất biến về nội dung;
-- chỉ phần trạng thái thanh toán đổi khi worker gọi Payment xong.
CREATE TABLE order_book_trades (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_reference        VARCHAR(50)   NOT NULL,
    order_book_id          BIGINT        NOT NULL,
    listing_id             BIGINT        NOT NULL,
    bid_order_id           BIGINT        NOT NULL,
    ask_order_id           BIGINT        NOT NULL,
    buyer_id               VARCHAR(100)  NOT NULL,
    seller_id              VARCHAR(100)  NOT NULL,

    -- Bên chủ động: lệnh vừa vào sổ và chạm lệnh đang nằm chờ. Giá khớp là giá của bên nằm chờ.
    aggressor_side         VARCHAR(4)    NOT NULL,
    price_permille         INT           NOT NULL,
    quantity               INT           NOT NULL,

    -- Tổng tiền người mua trả, phí nền tảng, tiền người bán nhận và tổng dư nợ gốc của các Note
    -- tại lúc khớp. Chụp lại thay vì tính lại: phí là policy có thể đổi, lịch sử thì không.
    amount                 NUMERIC(18,2) NOT NULL,
    platform_fee           NUMERIC(18,2) NOT NULL,
    seller_proceeds        NUMERIC(18,2) NOT NULL,
    outstanding_total      NUMERIC(18,2) NOT NULL,
    defaulted              BOOLEAN       NOT NULL,

    -- Thanh toán chạy sau khi khớp, bởi worker gọi Payment với mã chống trùng trade_reference.
    settlement_status      VARCHAR(20)   NOT NULL,
    settlement_attempts    INT           NOT NULL DEFAULT 0,
    next_settlement_at     TIMESTAMPTZ,
    last_settlement_error  VARCHAR(100),
    settled_at             TIMESTAMPTZ,

    executed_at            TIMESTAMPTZ   NOT NULL,
    created_at             TIMESTAMPTZ   NOT NULL,
    updated_at             TIMESTAMPTZ   NOT NULL,

    CONSTRAINT fk_order_book_trades_book FOREIGN KEY (order_book_id) REFERENCES order_books (id),
    CONSTRAINT fk_order_book_trades_bid FOREIGN KEY (bid_order_id) REFERENCES order_book_orders (id),
    CONSTRAINT fk_order_book_trades_ask FOREIGN KEY (ask_order_id) REFERENCES order_book_orders (id),
    CONSTRAINT ck_order_book_trades_parties CHECK (buyer_id <> seller_id),
    CONSTRAINT ck_order_book_trades_aggressor CHECK (aggressor_side IN ('BID', 'ASK')),
    CONSTRAINT ck_order_book_trades_price CHECK (price_permille BETWEEN 1 AND 1000),
    CONSTRAINT ck_order_book_trades_quantity CHECK (quantity > 0),
    CONSTRAINT ck_order_book_trades_amount CHECK (amount > 0 AND amount <= outstanding_total),
    CONSTRAINT ck_order_book_trades_fee_balanced CHECK (
        platform_fee >= 0 AND seller_proceeds >= 0 AND seller_proceeds + platform_fee = amount),
    CONSTRAINT ck_order_book_trades_settlement CHECK (
        settlement_status IN ('PENDING', 'SETTLED', 'FAILED')
        AND ((settlement_status = 'SETTLED') = (settled_at IS NOT NULL)))
);

CREATE UNIQUE INDEX uq_order_book_trades_trade_reference ON order_book_trades (trade_reference);
CREATE INDEX idx_order_book_trades_book_executed_at ON order_book_trades (order_book_id, executed_at DESC, id DESC);
CREATE INDEX idx_order_book_trades_bid_order_id ON order_book_trades (bid_order_id);

-- Trang quản trị: mọi lần khớp mới nhất trước, và lọc theo trạng thái thanh toán (đối soát).
CREATE INDEX idx_order_book_trades_executed_at ON order_book_trades (executed_at DESC, id DESC);
CREATE INDEX idx_order_book_trades_settlement_status_executed_at
    ON order_book_trades (settlement_status, executed_at DESC, id DESC);
CREATE INDEX idx_order_book_trades_settlement_pending
    ON order_book_trades (next_settlement_at, id)
    WHERE settlement_status = 'PENDING';

-- Lịch sử chuyển nhượng dùng chung cho bảng tin cũ và sổ lệnh mới: mỗi Note đổi chủ một dòng.
-- Dòng từ bảng tin cũ có note_listing_id, dòng từ sổ lệnh có trade_id; một trade gồm nhiều Note
-- nên chung payment_reference (= trade_reference) — unique cũ theo payment_reference chỉ còn áp
-- cho dòng của bảng tin.
ALTER TABLE note_transfers ALTER COLUMN note_listing_id DROP NOT NULL;
ALTER TABLE note_transfers ADD COLUMN trade_id BIGINT;
ALTER TABLE note_transfers ADD CONSTRAINT fk_note_transfers_trade
    FOREIGN KEY (trade_id) REFERENCES order_book_trades (id);
ALTER TABLE note_transfers ADD CONSTRAINT ck_note_transfers_source
    CHECK ((note_listing_id IS NULL) <> (trade_id IS NULL));

DROP INDEX ux_note_transfer_payment;
CREATE UNIQUE INDEX uq_note_transfers_payment_reference
    ON note_transfers (payment_reference)
    WHERE trade_id IS NULL;
CREATE UNIQUE INDEX uq_note_transfers_trade_id_note_id
    ON note_transfers (trade_id, note_id)
    WHERE trade_id IS NOT NULL;

-- Bảng tin bị thay bởi sổ lệnh: rút mọi tin còn mở. Lịch sử tin đã bán giữ nguyên.
UPDATE note_listings
SET status = 'CANCELLED',
    cancelled_at = NOW(),
    updated_by = 'SYSTEM_ORDER_BOOK_MIGRATION',
    updated_at = NOW()
WHERE status = 'OPEN';
