CREATE TABLE loan_outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_version INTEGER NOT NULL,
    payload_json JSONB NOT NULL,
    status VARCHAR(30) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL,
    processing_started_at TIMESTAMPTZ,
    processing_token UUID,
    published_at TIMESTAMPTZ,
    last_error_code VARCHAR(50),
    last_error_detail VARCHAR(500),
    trace_id VARCHAR(100) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_loan_outbox_events_event_id UNIQUE (event_id),
    CONSTRAINT ck_loan_outbox_event_version CHECK (event_version > 0),
    CONSTRAINT ck_loan_outbox_attempt CHECK (attempt_count >= 0),
    CONSTRAINT ck_loan_outbox_status CHECK (status IN (
        'PENDING', 'PROCESSING', 'PUBLISHED', 'DEAD_LETTER'
    )),
    CONSTRAINT ck_loan_outbox_state CHECK (
        (status = 'PENDING' AND processing_started_at IS NULL AND processing_token IS NULL AND published_at IS NULL)
        OR (status = 'PROCESSING' AND processing_started_at IS NOT NULL AND processing_token IS NOT NULL AND published_at IS NULL)
        OR (status = 'PUBLISHED' AND processing_started_at IS NOT NULL AND processing_token IS NULL AND published_at IS NOT NULL)
        OR (status = 'DEAD_LETTER' AND processing_started_at IS NOT NULL AND processing_token IS NULL AND published_at IS NULL)
    )
);

CREATE INDEX idx_loan_outbox_events_due
    ON loan_outbox_events (available_at, id)
    WHERE status = 'PENDING';

CREATE INDEX idx_loan_outbox_events_processing_lease
    ON loan_outbox_events (processing_started_at, id)
    WHERE status = 'PROCESSING';

CREATE INDEX idx_loan_outbox_events_aggregate
    ON loan_outbox_events (aggregate_type, aggregate_id, created_at, id);
