-- Funding state thuộc Loan Application; Investment vẫn sở hữu listing/order/commitment.
ALTER TABLE loan_applications
    ADD COLUMN funding_status VARCHAR(30),
    ADD COLUMN funding_round INTEGER,
    ADD COLUMN listing_version INTEGER,
    ADD COLUMN funding_requested_at TIMESTAMPTZ,
    ADD COLUMN investment_listing_id BIGINT,
    ADD COLUMN funded_amount NUMERIC(18,2),
    ADD COLUMN allocation_version BIGINT,
    ADD COLUMN allocation_hash VARCHAR(64),
    ADD COLUMN allocation_snapshot_json JSONB,
    ADD COLUMN funding_completed_at TIMESTAMPTZ;

ALTER TABLE loan_applications
    ADD CONSTRAINT ck_loan_applications_funding_status
        CHECK (funding_status IS NULL OR funding_status IN ('REQUESTED', 'FULLY_FUNDED')),
    ADD CONSTRAINT ck_loan_applications_funding_request_complete
        CHECK (
            funding_status IS NULL
            OR (funding_round > 0 AND listing_version > 0 AND funding_requested_at IS NOT NULL)
        ),
    ADD CONSTRAINT ck_loan_applications_fully_funded_complete
        CHECK (
            funding_status <> 'FULLY_FUNDED'
            OR (
                investment_listing_id IS NOT NULL
                AND funded_amount = requested_amount
                AND allocation_version > 0
                AND allocation_hash IS NOT NULL
                AND allocation_snapshot_json IS NOT NULL
                AND funding_completed_at IS NOT NULL
            )
        );

CREATE UNIQUE INDEX uq_loan_applications_investment_listing
    ON loan_applications (investment_listing_id)
    WHERE investment_listing_id IS NOT NULL;

CREATE INDEX idx_loan_applications_funding_status_requested_at
    ON loan_applications (funding_status, funding_requested_at, id)
    WHERE funding_status IS NOT NULL;

-- Event Contract nội bộ không được vô tình phát ra Kafka khi bật relay.
ALTER TABLE loan_outbox_events
    ADD COLUMN publishable BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX idx_loan_outbox_events_publishable_due
    ON loan_outbox_events (available_at, id)
    WHERE publishable = TRUE AND status IN ('PENDING', 'PROCESSING');

-- Dấu idempotency consumer cho event Investment → Loan.
CREATE TABLE loan_processed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_version INTEGER NOT NULL,
    source VARCHAR(50) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_loan_processed_events_event_id UNIQUE (event_id)
);

CREATE INDEX idx_loan_processed_events_source_aggregate
    ON loan_processed_events (source, aggregate_id, processed_at DESC);
