-- Một Contract chứa borrower và toàn bộ lender allocations; không nhân bản Contract theo investor.
ALTER TABLE loan_contracts
    ADD COLUMN multi_party BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE loan_contracts DROP CONSTRAINT ck_loan_contract_status;
ALTER TABLE loan_contracts ADD CONSTRAINT ck_loan_contract_status CHECK (status IN (
    'PENDING_LENDER_SIGNATURES', 'PENDING_BORROWER_SIGNATURE',
    'PENDING_SIGNATURE', 'SIGNING', 'SIGNED', 'DECLINED', 'EXPIRED', 'EFFECTIVE', 'COMPLETED'
));

ALTER TABLE loan_contract_status_histories DROP CONSTRAINT ck_contract_history_from_status;
ALTER TABLE loan_contract_status_histories ADD CONSTRAINT ck_contract_history_from_status CHECK (
    from_status IS NULL OR from_status IN (
        'PENDING_LENDER_SIGNATURES', 'PENDING_BORROWER_SIGNATURE',
        'PENDING_SIGNATURE', 'SIGNING', 'SIGNED', 'DECLINED', 'EXPIRED', 'EFFECTIVE', 'COMPLETED'
    )
);

ALTER TABLE loan_contract_status_histories DROP CONSTRAINT ck_contract_history_to_status;
ALTER TABLE loan_contract_status_histories ADD CONSTRAINT ck_contract_history_to_status CHECK (to_status IN (
    'PENDING_LENDER_SIGNATURES', 'PENDING_BORROWER_SIGNATURE',
    'PENDING_SIGNATURE', 'SIGNING', 'SIGNED', 'DECLINED', 'EXPIRED', 'EFFECTIVE', 'COMPLETED'
));

ALTER TABLE loan_contract_status_histories DROP CONSTRAINT ck_contract_history_actor;
ALTER TABLE loan_contract_status_histories ADD CONSTRAINT ck_contract_history_actor CHECK (
    actor_type IN ('BORROWER', 'INVESTOR', 'ADMIN', 'SYSTEM')
);

ALTER TABLE loan_contracts DROP CONSTRAINT ck_loan_contract_consent;
ALTER TABLE loan_contracts ADD CONSTRAINT ck_loan_contract_consent CHECK (
    (
        status IN ('PENDING_LENDER_SIGNATURES', 'PENDING_BORROWER_SIGNATURE', 'PENDING_SIGNATURE', 'EXPIRED')
        AND consent_idempotency_key IS NULL AND consent_request_hash IS NULL AND consent_action IS NULL
        AND signed_by IS NULL AND signed_at IS NULL AND signature_method IS NULL
        AND signature_provider IS NULL AND signature_transaction_id IS NULL
        AND signature_document_id IS NULL AND signature_requested_at IS NULL
        AND signature_evidence_hash IS NULL
        AND declined_by IS NULL AND declined_at IS NULL AND decline_reason_code IS NULL
    )
    OR
    (
        status = 'SIGNING'
        AND consent_idempotency_key IS NOT NULL AND consent_request_hash IS NOT NULL
        AND consent_action = 'SIGN'
        AND signed_by IS NULL AND signed_at IS NULL
        AND signature_method = 'VNPT_SMART_CA' AND signature_provider = 'VNPT_SMART_CA'
        AND signature_transaction_id IS NOT NULL AND signature_document_id IS NOT NULL
        AND signature_requested_at IS NOT NULL AND signature_evidence_hash IS NULL
        AND declined_by IS NULL AND declined_at IS NULL AND decline_reason_code IS NULL
    )
    OR
    (
        status IN ('SIGNED', 'EFFECTIVE', 'COMPLETED')
        AND consent_idempotency_key IS NOT NULL AND consent_request_hash IS NOT NULL
        AND consent_action = 'SIGN'
        AND signed_by IS NOT NULL AND signed_at IS NOT NULL
        AND signature_method IN ('CLICK_WRAP_MVP', 'VNPT_SMART_CA')
        AND signature_provider IN ('MOCK', 'VNPT_SMART_CA')
        AND signature_transaction_id IS NOT NULL AND length(signature_evidence_hash) = 64
        AND (
            (signature_provider = 'MOCK' AND signature_method = 'CLICK_WRAP_MVP')
            OR (
                signature_provider = 'VNPT_SMART_CA' AND signature_method = 'VNPT_SMART_CA'
                AND signature_document_id IS NOT NULL AND signature_requested_at IS NOT NULL
            )
        )
        AND declined_by IS NULL AND declined_at IS NULL AND decline_reason_code IS NULL
    )
    OR
    (
        status = 'DECLINED'
        AND consent_idempotency_key IS NOT NULL AND consent_request_hash IS NOT NULL
        AND consent_action = 'DECLINE'
        AND signed_by IS NULL AND signed_at IS NULL AND signature_method IS NULL
        AND signature_provider IS NULL AND signature_transaction_id IS NULL
        AND signature_document_id IS NULL AND signature_requested_at IS NULL
        AND signature_evidence_hash IS NULL
        AND declined_by IS NOT NULL AND declined_at IS NOT NULL AND decline_reason_code IS NOT NULL
    )
);

DROP INDEX idx_loan_contracts_pending_expiry;
CREATE INDEX idx_loan_contracts_pending_expiry ON loan_contracts (expires_at, id)
    WHERE status IN (
        'PENDING_LENDER_SIGNATURES', 'PENDING_BORROWER_SIGNATURE', 'PENDING_SIGNATURE', 'SIGNING'
    );

CREATE TABLE loan_contract_parties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    commitment_id BIGINT,
    party_type VARCHAR(20) NOT NULL,
    party_id VARCHAR(100) NOT NULL,
    allocation_amount NUMERIC(18,2),
    allocation_share_percent NUMERIC(9,6),
    status VARCHAR(30) NOT NULL,
    signature_method VARCHAR(30),
    signature_provider VARCHAR(30),
    signature_transaction_id VARCHAR(150),
    signature_evidence_hash VARCHAR(64),
    idempotency_key VARCHAR(150),
    request_hash VARCHAR(64),
    signed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_contract_party_contract FOREIGN KEY (contract_id) REFERENCES loan_contracts (id),
    CONSTRAINT uq_contract_party_commitment UNIQUE (contract_id, commitment_id),
    CONSTRAINT ck_contract_party_type CHECK (party_type IN ('BORROWER', 'LENDER')),
    CONSTRAINT ck_contract_party_status CHECK (status IN ('PENDING_SIGNATURE', 'SIGNED', 'DECLINED', 'EXPIRED')),
    CONSTRAINT ck_contract_party_allocation CHECK (
        (party_type = 'BORROWER' AND commitment_id IS NULL
            AND allocation_amount IS NULL AND allocation_share_percent IS NULL)
        OR
        (party_type = 'LENDER' AND commitment_id IS NOT NULL
            AND allocation_amount > 0 AND allocation_share_percent > 0)
    ),
    CONSTRAINT ck_contract_party_signature CHECK (
        (status = 'PENDING_SIGNATURE' AND signature_method IS NULL AND signature_provider IS NULL
            AND signature_transaction_id IS NULL AND signature_evidence_hash IS NULL
            AND idempotency_key IS NULL AND request_hash IS NULL AND signed_at IS NULL)
        OR
        (status = 'SIGNED' AND signature_method IS NOT NULL AND signature_provider IS NOT NULL
            AND signature_transaction_id IS NOT NULL AND length(signature_evidence_hash) = 64
            AND idempotency_key IS NOT NULL AND length(request_hash) = 64 AND signed_at IS NOT NULL)
        OR status IN ('DECLINED', 'EXPIRED')
    )
);

CREATE INDEX idx_contract_parties_contract_status
    ON loan_contract_parties (contract_id, party_type, status, id);
CREATE INDEX idx_contract_parties_party_created
    ON loan_contract_parties (party_id, created_at DESC, id DESC);
CREATE UNIQUE INDEX uq_contract_party_idempotency
    ON loan_contract_parties (contract_id, party_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX uq_contract_borrower_party
    ON loan_contract_parties (contract_id)
    WHERE party_type = 'BORROWER';
