CREATE TABLE loan_disbursement_sagas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saga_id UUID NOT NULL,
    loan_application_id BIGINT NOT NULL,
    contract_number VARCHAR(50) NOT NULL,
    listing_id BIGINT NOT NULL,
    borrower_id VARCHAR(100) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(40) NOT NULL,
    payment_reference VARCHAR(100),
    fineract_loan_id BIGINT,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ,
    last_error_code VARCHAR(80),
    last_error_detail VARCHAR(500),
    disbursed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_loan_disbursement_saga_id UNIQUE (saga_id),
    CONSTRAINT uq_loan_disbursement_application UNIQUE (loan_application_id),
    CONSTRAINT uq_loan_disbursement_contract UNIQUE (contract_number),
    CONSTRAINT uq_loan_disbursement_payment_reference UNIQUE (payment_reference),
    CONSTRAINT ck_loan_disbursement_amount CHECK (amount > 0),
    CONSTRAINT ck_loan_disbursement_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_loan_disbursement_attempt CHECK (attempt_count >= 0),
    CONSTRAINT ck_loan_disbursement_status CHECK (status IN (
        'WAITING_PAYMENT', 'CORE_BOOKING_PENDING', 'CORE_BOOKING',
        'RETRY_PENDING', 'REPAIR_REQUIRED', 'COMPLETED', 'PAYMENT_FAILED'
    ))
);

CREATE INDEX idx_loan_disbursement_saga_due
    ON loan_disbursement_sagas (next_retry_at, id)
    WHERE status IN ('CORE_BOOKING_PENDING', 'RETRY_PENDING');

