CREATE TABLE finora_loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_number VARCHAR(50) NOT NULL,
    loan_application_id BIGINT NOT NULL,
    application_number VARCHAR(50) NOT NULL,
    contract_number VARCHAR(50) NOT NULL,
    borrower_id VARCHAR(100) NOT NULL,
    fineract_loan_id BIGINT NOT NULL,
    principal_amount NUMERIC(18, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(30) NOT NULL,
    disbursed_at TIMESTAMPTZ NOT NULL,
    closed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_finora_loans_number UNIQUE (loan_number),
    CONSTRAINT uq_finora_loans_application UNIQUE (loan_application_id),
    CONSTRAINT uq_finora_loans_application_number UNIQUE (application_number),
    CONSTRAINT uq_finora_loans_contract UNIQUE (contract_number),
    CONSTRAINT uq_finora_loans_fineract UNIQUE (fineract_loan_id),
    CONSTRAINT fk_finora_loans_application FOREIGN KEY (loan_application_id) REFERENCES loan_applications (id),
    CONSTRAINT ck_finora_loans_principal CHECK (principal_amount > 0),
    CONSTRAINT ck_finora_loans_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_finora_loans_status CHECK (status IN (
        'ACTIVE', 'RESTRUCTURING', 'SETTLED', 'DEFAULTED', 'WRITTEN_OFF'
    ))
);

CREATE INDEX idx_finora_loans_borrower_status
    ON finora_loans (borrower_id, status, disbursed_at DESC, id DESC);

CREATE TABLE loan_servicing_projections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finora_loan_id BIGINT NOT NULL,
    fineract_status_code VARCHAR(50) NOT NULL,
    principal_disbursed NUMERIC(18, 2) NOT NULL,
    principal_paid NUMERIC(18, 2) NOT NULL,
    principal_outstanding NUMERIC(18, 2) NOT NULL,
    interest_charged NUMERIC(18, 2) NOT NULL,
    interest_paid NUMERIC(18, 2) NOT NULL,
    interest_outstanding NUMERIC(18, 2) NOT NULL,
    fee_outstanding NUMERIC(18, 2) NOT NULL,
    penalty_outstanding NUMERIC(18, 2) NOT NULL,
    total_outstanding NUMERIC(18, 2) NOT NULL,
    overdue_amount NUMERIC(18, 2) NOT NULL,
    overdue_since DATE,
    days_past_due INTEGER NOT NULL DEFAULT 0,
    next_due_date DATE,
    next_due_amount NUMERIC(18, 2),
    maturity_date DATE,
    source VARCHAR(40) NOT NULL,
    data_as_of TIMESTAMPTZ NOT NULL,
    last_synced_at TIMESTAMPTZ NOT NULL,
    stale BOOLEAN NOT NULL,
    projection_version BIGINT NOT NULL DEFAULT 1,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_loan_servicing_projection_loan UNIQUE (finora_loan_id),
    CONSTRAINT fk_loan_servicing_projection_loan FOREIGN KEY (finora_loan_id) REFERENCES finora_loans (id),
    CONSTRAINT ck_loan_servicing_projection_money CHECK (
        principal_disbursed >= 0 AND principal_paid >= 0 AND principal_outstanding >= 0
        AND interest_charged >= 0 AND interest_paid >= 0 AND interest_outstanding >= 0
        AND fee_outstanding >= 0 AND penalty_outstanding >= 0
        AND total_outstanding >= 0 AND overdue_amount >= 0
    ),
    CONSTRAINT ck_loan_servicing_projection_dpd CHECK (days_past_due >= 0),
    CONSTRAINT ck_loan_servicing_projection_version CHECK (projection_version > 0)
);

CREATE INDEX idx_loan_servicing_projection_due
    ON loan_servicing_projections (next_due_date, finora_loan_id)
    WHERE next_due_date IS NOT NULL AND total_outstanding > 0;
