CREATE TABLE loan_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    min_amount NUMERIC(18, 2) NOT NULL,
    max_amount NUMERIC(18, 2) NOT NULL,
    min_term_months SMALLINT NOT NULL,
    max_term_months SMALLINT NOT NULL,
    annual_interest_rate NUMERIC(7, 4) NOT NULL,
    repayment_method VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    core_sync_status VARCHAR(20) NOT NULL,
    current_core_mapping_id BIGINT,
    configuration_version BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_loan_product_amount CHECK (min_amount > 0 AND max_amount >= min_amount),
    CONSTRAINT ck_loan_product_term CHECK (min_term_months > 0 AND max_term_months >= min_term_months),
    CONSTRAINT ck_loan_product_rate CHECK (annual_interest_rate > 0),
    CONSTRAINT ck_loan_product_repayment_method CHECK (repayment_method IN ('ANNUITY', 'EQUAL_PRINCIPAL')),
    CONSTRAINT ck_loan_product_status CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED')),
    CONSTRAINT ck_loan_product_core_sync CHECK (core_sync_status IN ('NOT_SYNCED', 'PENDING', 'SYNCED', 'FAILED'))
);

CREATE TABLE fineract_product_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_product_id BIGINT NOT NULL,
    finora_product_version BIGINT NOT NULL,
    fineract_product_id BIGINT UNIQUE,
    external_id VARCHAR(100) NOT NULL UNIQUE,
    config_version VARCHAR(30) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    last_error_code VARCHAR(100),
    last_error_detail VARCHAR(1000),
    synced_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_fineract_mapping_product FOREIGN KEY (loan_product_id) REFERENCES loan_products (id),
    CONSTRAINT uq_fineract_mapping_product_version UNIQUE (loan_product_id, finora_product_version),
    CONSTRAINT ck_fineract_mapping_status CHECK (status IN ('PENDING', 'SYNCED', 'FAILED'))
);

ALTER TABLE loan_products
    ADD CONSTRAINT fk_loan_product_current_mapping
    FOREIGN KEY (current_core_mapping_id) REFERENCES fineract_product_mappings (id);

CREATE TABLE fineract_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_id VARCHAR(36) NOT NULL UNIQUE,
    command_type VARCHAR(50) NOT NULL,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    mapping_id BIGINT NOT NULL,
    idempotency_key VARCHAR(150) NOT NULL UNIQUE,
    request_hash VARCHAR(64) NOT NULL,
    request_snapshot_json JSONB NOT NULL,
    response_snapshot_json JSONB,
    status VARCHAR(30) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error_code VARCHAR(100),
    last_error_detail VARCHAR(1000),
    next_retry_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_fineract_command_product FOREIGN KEY (aggregate_id) REFERENCES loan_products (id),
    CONSTRAINT fk_fineract_command_mapping FOREIGN KEY (mapping_id) REFERENCES fineract_product_mappings (id),
    CONSTRAINT ck_fineract_command_type CHECK (command_type IN ('CREATE_PRODUCT')),
    CONSTRAINT ck_fineract_command_status CHECK (status IN ('PENDING', 'PROCESSING', 'RETRY_PENDING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_fineract_command_attempt CHECK (attempt_count >= 0)
);

-- Danh mục borrower chỉ quét ACTIVE; worker chỉ quét command retry đến hạn.
CREATE INDEX idx_loan_products_catalog ON loan_products (status, updated_at DESC, id DESC);
CREATE INDEX idx_fineract_mappings_product ON fineract_product_mappings (loan_product_id, created_at DESC);
CREATE INDEX idx_fineract_commands_retry ON fineract_commands (status, next_retry_at, id);
CREATE INDEX idx_fineract_commands_aggregate ON fineract_commands (aggregate_type, aggregate_id, created_at DESC);
