CREATE TABLE loan_reschedule_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id UUID NOT NULL,
    finora_loan_id BIGINT NOT NULL,
    loan_number VARCHAR(50) NOT NULL,
    borrower_id VARCHAR(100) NOT NULL,
    request_type VARCHAR(40) NOT NULL,
    reschedule_from_date DATE NOT NULL,
    adjusted_due_date DATE,
    extra_terms INTEGER,
    reason_comment VARCHAR(500) NOT NULL,
    terms_version VARCHAR(50) NOT NULL,
    terms_hash VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(150) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(40) NOT NULL,
    fineract_reschedule_id BIGINT,
    admin_id VARCHAR(100),
    decision_comment VARCHAR(500),
    decision_idempotency_key VARCHAR(150),
    decided_at TIMESTAMPTZ,
    original_maturity_date DATE,
    new_maturity_date DATE,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ,
    processing_started_at TIMESTAMPTZ,
    last_error_code VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_loan_reschedule_request_id UNIQUE (request_id),
    CONSTRAINT uq_loan_reschedule_idempotency UNIQUE (borrower_id, idempotency_key),
    CONSTRAINT fk_loan_reschedule_loan FOREIGN KEY (finora_loan_id) REFERENCES finora_loans (id),
    CONSTRAINT ck_loan_reschedule_type CHECK (request_type IN ('INSTALLMENT_ADJUSTMENT', 'TERM_EXTENSION')),
    CONSTRAINT ck_loan_reschedule_status CHECK (status IN (
        'PENDING_REVIEW', 'REJECTED', 'CREATE_PENDING', 'CREATING', 'APPROVAL_PENDING',
        'APPROVING', 'COMPLETED', 'RECONCILIATION_REQUIRED', 'MANUAL_REVIEW'
    )),
    CONSTRAINT ck_loan_reschedule_attempt CHECK (attempt_count >= 0),
    CONSTRAINT ck_loan_reschedule_shape CHECK (
        (request_type = 'INSTALLMENT_ADJUSTMENT' AND adjusted_due_date IS NOT NULL AND extra_terms IS NULL)
        OR (request_type = 'TERM_EXTENSION' AND adjusted_due_date IS NULL AND extra_terms > 0)
    )
);

CREATE UNIQUE INDEX uq_loan_reschedule_one_active_per_loan
    ON loan_reschedule_requests (finora_loan_id)
    WHERE status IN (
        'PENDING_REVIEW', 'CREATE_PENDING', 'CREATING', 'APPROVAL_PENDING',
        'APPROVING', 'RECONCILIATION_REQUIRED', 'MANUAL_REVIEW'
    );

CREATE INDEX idx_loan_reschedule_borrower_list
    ON loan_reschedule_requests (borrower_id, loan_number, created_at DESC, id DESC);

CREATE INDEX idx_loan_reschedule_admin_list
    ON loan_reschedule_requests (status, created_at DESC, id DESC);

CREATE INDEX idx_loan_reschedule_worker_due
    ON loan_reschedule_requests (status, next_attempt_at, id)
    WHERE status IN ('CREATE_PENDING', 'APPROVAL_PENDING', 'RECONCILIATION_REQUIRED', 'CREATING', 'APPROVING');
