CREATE TABLE loan_collection_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id UUID NOT NULL,
    finora_loan_id BIGINT NOT NULL,
    loan_number VARCHAR(50) NOT NULL,
    borrower_id VARCHAR(100) NOT NULL,
    stage VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    days_past_due INTEGER NOT NULL,
    debt_group INTEGER NOT NULL,
    overdue_amount NUMERIC(18, 2) NOT NULL,
    total_outstanding NUMERIC(18, 2) NOT NULL,
    overdue_since DATE,
    opened_at TIMESTAMPTZ NOT NULL,
    last_observed_at TIMESTAMPTZ NOT NULL,
    closed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_loan_collection_case_id UNIQUE (case_id),
    CONSTRAINT fk_loan_collection_case_loan FOREIGN KEY (finora_loan_id) REFERENCES finora_loans (id),
    CONSTRAINT ck_collection_stage CHECK (stage IN (
        'EARLY_REMINDER', 'ATTENTION', 'NPL', 'INTENSIVE', 'LOSS'
    )),
    CONSTRAINT ck_collection_status CHECK (status IN ('OPEN', 'CURED', 'SETTLED', 'WRITTEN_OFF')),
    CONSTRAINT ck_collection_dpd CHECK (days_past_due >= 0 AND debt_group BETWEEN 1 AND 5),
    CONSTRAINT ck_collection_money CHECK (overdue_amount >= 0 AND total_outstanding >= 0)
);

CREATE UNIQUE INDEX uq_collection_one_open_per_loan
    ON loan_collection_cases (finora_loan_id) WHERE status = 'OPEN';
CREATE INDEX idx_collection_admin_queue
    ON loan_collection_cases (status, stage, days_past_due DESC, updated_at, id);
CREATE INDEX idx_collection_loan_history
    ON loan_collection_cases (finora_loan_id, opened_at DESC, id DESC);

CREATE TABLE loan_collection_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_id UUID NOT NULL,
    collection_case_id BIGINT NOT NULL,
    action_type VARCHAR(40) NOT NULL,
    note VARCHAR(500),
    promise_date DATE,
    promise_amount NUMERIC(18, 2),
    actor_id VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(150) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_collection_action_id UNIQUE (action_id),
    CONSTRAINT uq_collection_action_idempotency UNIQUE (actor_id, idempotency_key),
    CONSTRAINT fk_collection_action_case FOREIGN KEY (collection_case_id) REFERENCES loan_collection_cases (id),
    CONSTRAINT ck_collection_action_type CHECK (action_type IN (
        'REMINDER_SENT', 'BORROWER_CONTACTED', 'PROMISE_TO_PAY', 'LEGAL_REVIEW',
        'FIELD_COLLECTION', 'WRITE_OFF_RECOMMENDED', 'NOTE'
    )),
    CONSTRAINT ck_collection_promise_amount CHECK (promise_amount IS NULL OR promise_amount > 0)
);

CREATE INDEX idx_collection_action_timeline
    ON loan_collection_actions (collection_case_id, created_at DESC, id DESC);

