CREATE TABLE loan_reconciliation_incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id UUID NOT NULL,
    finora_loan_id BIGINT NOT NULL,
    loan_number VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    expected_value VARCHAR(200) NOT NULL,
    actual_value VARCHAR(200) NOT NULL,
    occurrence_count INTEGER NOT NULL DEFAULT 1,
    first_detected_at TIMESTAMPTZ NOT NULL,
    last_detected_at TIMESTAMPTZ NOT NULL,
    resolved_at TIMESTAMPTZ,
    resolution_code VARCHAR(60),
    resolved_by VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_loan_reconciliation_incident_id UNIQUE (incident_id),
    CONSTRAINT fk_loan_reconciliation_incident_loan
        FOREIGN KEY (finora_loan_id) REFERENCES finora_loans (id),
    CONSTRAINT ck_loan_reconciliation_incident_type CHECK (type IN (
        'CORE_LOAN_ID_MISMATCH', 'EXTERNAL_ID_MISMATCH',
        'PRINCIPAL_DISBURSED_MISMATCH', 'OUTSTANDING_BREAKDOWN_MISMATCH'
    )),
    CONSTRAINT ck_loan_reconciliation_incident_status CHECK (status IN ('OPEN', 'RESOLVED')),
    CONSTRAINT ck_loan_reconciliation_incident_occurrences CHECK (occurrence_count > 0),
    CONSTRAINT ck_loan_reconciliation_incident_resolution CHECK (
        (status = 'OPEN' AND resolved_at IS NULL AND resolution_code IS NULL AND resolved_by IS NULL)
        OR (status = 'RESOLVED' AND resolved_at IS NOT NULL AND resolution_code IS NOT NULL AND resolved_by IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_loan_reconciliation_one_open_type
    ON loan_reconciliation_incidents (finora_loan_id, type) WHERE status = 'OPEN';
CREATE INDEX idx_loan_reconciliation_admin_queue
    ON loan_reconciliation_incidents (status, updated_at, id);
CREATE INDEX idx_loan_reconciliation_history
    ON loan_reconciliation_incidents (finora_loan_id, first_detected_at DESC, id DESC);
