CREATE TABLE loan_repayment_event_quarantine (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    loan_application_id BIGINT NOT NULL,
    repayment_id UUID NOT NULL,
    payload_json TEXT NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL,
    reason_code VARCHAR(60) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_loan_repayment_event_quarantine_event UNIQUE (event_id),
    CONSTRAINT ck_loan_repayment_event_quarantine_status CHECK (status IN ('PENDING','RESOLVED')),
    CONSTRAINT ck_loan_repayment_event_quarantine_attempt CHECK (attempt_count >= 0)
);

CREATE INDEX idx_loan_repayment_event_quarantine_work
    ON loan_repayment_event_quarantine (status, created_at, id);

CREATE INDEX idx_loan_repayment_event_quarantine_application
    ON loan_repayment_event_quarantine (loan_application_id, status, id);
