CREATE TABLE loan_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_number VARCHAR(30) NOT NULL UNIQUE,
    borrower_id VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(150) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    loan_product_id BIGINT NOT NULL,
    requested_amount NUMERIC(18, 2) NOT NULL,
    requested_term_months SMALLINT NOT NULL,
    purpose_code VARCHAR(30) NOT NULL,
    purpose_detail VARCHAR(500),
    declared_monthly_income NUMERIC(18, 2) NOT NULL,
    annual_income_snapshot NUMERIC(18, 2) NOT NULL,
    employment_length_months SMALLINT,
    education_level VARCHAR(30),
    home_ownership VARCHAR(20) NOT NULL,
    monthly_debt_obligations NUMERIC(18, 2) NOT NULL,
    dti_snapshot NUMERIC(9, 4) NOT NULL,
    financial_information_source VARCHAR(30) NOT NULL,
    financial_information_captured_at TIMESTAMPTZ NOT NULL,
    product_code_snapshot VARCHAR(50) NOT NULL,
    product_name_snapshot VARCHAR(150) NOT NULL,
    product_configuration_version_snapshot BIGINT NOT NULL,
    product_min_amount_snapshot NUMERIC(18, 2) NOT NULL,
    product_max_amount_snapshot NUMERIC(18, 2) NOT NULL,
    product_min_term_months_snapshot SMALLINT NOT NULL,
    product_max_term_months_snapshot SMALLINT NOT NULL,
    annual_interest_rate_snapshot NUMERIC(7, 4) NOT NULL,
    repayment_method_snapshot VARCHAR(30) NOT NULL,
    fineract_product_id_snapshot BIGINT NOT NULL,
    core_mapping_id_snapshot BIGINT NOT NULL,
    core_config_version_snapshot VARCHAR(30) NOT NULL,
    expected_disbursement_date DATE NOT NULL,
    submission_calculation_snapshot_id BIGINT,
    pricing_disclosure_version_snapshot VARCHAR(50) NOT NULL,
    pricing_disclosure_accepted_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(30) NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL,
    withdrawn_at TIMESTAMPTZ,
    withdrawal_reason VARCHAR(500),
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_loan_application_idempotency UNIQUE (borrower_id, idempotency_key),
    CONSTRAINT fk_loan_application_product FOREIGN KEY (loan_product_id) REFERENCES loan_products (id),
    CONSTRAINT fk_loan_application_mapping FOREIGN KEY (core_mapping_id_snapshot) REFERENCES fineract_product_mappings (id),
    CONSTRAINT ck_loan_application_amount CHECK (requested_amount > 0),
    CONSTRAINT ck_loan_application_term CHECK (requested_term_months > 0),
    CONSTRAINT ck_loan_application_income CHECK (declared_monthly_income > 0),
    CONSTRAINT ck_loan_application_employment CHECK (employment_length_months IS NULL OR employment_length_months >= 0),
    CONSTRAINT ck_loan_application_debt CHECK (monthly_debt_obligations >= 0),
    CONSTRAINT ck_loan_application_dti CHECK (dti_snapshot >= 0),
    CONSTRAINT ck_loan_application_purpose CHECK (purpose_code IN (
        'DEBT_CONSOLIDATION', 'CREDIT_CARD', 'HOME_IMPROVEMENT', 'MAJOR_PURCHASE',
        'MEDICAL', 'CAR', 'SMALL_BUSINESS', 'MOVING', 'VACATION', 'EDUCATION', 'OTHER'
    )),
    CONSTRAINT ck_loan_application_status CHECK (status IN ('SUBMITTED', 'WITHDRAWN')),
    CONSTRAINT ck_loan_application_repayment CHECK (repayment_method_snapshot IN ('ANNUITY', 'EQUAL_PRINCIPAL')),
    CONSTRAINT ck_loan_application_home CHECK (home_ownership IN ('RENT', 'OWN', 'MORTGAGE', 'OTHER')),
    CONSTRAINT ck_loan_application_education CHECK (
        education_level IS NULL OR education_level IN ('HIGH_SCHOOL', 'COLLEGE', 'UNIVERSITY', 'POSTGRADUATE', 'OTHER')
    ),
    CONSTRAINT ck_loan_application_source CHECK (financial_information_source IN ('SELF_DECLARED'))
);

CREATE TABLE schedule_calculation_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL UNIQUE,
    purpose VARCHAR(30) NOT NULL,
    request_id VARCHAR(100) NOT NULL UNIQUE,
    fineract_product_id BIGINT NOT NULL,
    expected_disbursement_date DATE NOT NULL,
    request_snapshot_json JSONB NOT NULL,
    periods_snapshot_json JSONB NOT NULL,
    total_principal NUMERIC(18, 2) NOT NULL,
    total_interest NUMERIC(18, 2) NOT NULL,
    total_fees NUMERIC(18, 2) NOT NULL,
    total_penalties NUMERIC(18, 2) NOT NULL,
    total_repayment NUMERIC(18, 2) NOT NULL,
    first_installment NUMERIC(18, 2) NOT NULL,
    maximum_installment NUMERIC(18, 2) NOT NULL,
    response_hash VARCHAR(64) NOT NULL,
    calculation_policy_version VARCHAR(50) NOT NULL,
    calculated_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_schedule_snapshot_application FOREIGN KEY (application_id) REFERENCES loan_applications (id),
    CONSTRAINT ck_schedule_snapshot_purpose CHECK (purpose IN ('PREVIEW', 'SUBMISSION_SCORING'))
);

ALTER TABLE loan_applications
    ADD CONSTRAINT fk_loan_application_submission_calculation
    FOREIGN KEY (submission_calculation_snapshot_id) REFERENCES schedule_calculation_snapshots (id);

CREATE TABLE loan_application_status_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_application_id BIGINT NOT NULL,
    from_status VARCHAR(30),
    to_status VARCHAR(30) NOT NULL,
    reason_code VARCHAR(50),
    reason_detail VARCHAR(1000),
    actor_type VARCHAR(20) NOT NULL,
    actor_id VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_application_history_application FOREIGN KEY (loan_application_id) REFERENCES loan_applications (id),
    CONSTRAINT ck_application_history_from_status CHECK (from_status IS NULL OR from_status IN ('SUBMITTED', 'WITHDRAWN')),
    CONSTRAINT ck_application_history_to_status CHECK (to_status IN ('SUBMITTED', 'WITHDRAWN')),
    CONSTRAINT ck_application_history_actor CHECK (actor_type IN ('BORROWER', 'ADMIN', 'SYSTEM'))
);

-- Các index bám theo truy vấn thực tế, không index mọi cột: danh sách của borrower và timeline.
CREATE INDEX idx_loan_applications_borrower_created
    ON loan_applications (borrower_id, created_at DESC, id DESC);
CREATE INDEX idx_loan_applications_status_created
    ON loan_applications (status, created_at, id);
CREATE INDEX idx_loan_applications_product
    ON loan_applications (loan_product_id, created_at DESC, id DESC);
CREATE INDEX idx_application_histories_timeline
    ON loan_application_status_histories (loan_application_id, created_at DESC, id DESC);
