CREATE TABLE borrower_eligibility_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    borrower_id VARCHAR(100) NOT NULL,
    request_id VARCHAR(100) NOT NULL UNIQUE,
    age SMALLINT,
    kyc_status VARCHAR(30) NOT NULL,
    kyc_reference VARCHAR(100),
    kyc_version VARCHAR(50),
    income_verification_status VARCHAR(30) NOT NULL,
    profile_source VARCHAR(30) NOT NULL,
    eligibility_result VARCHAR(30) NOT NULL,
    reason_code VARCHAR(100),
    request_hash VARCHAR(64) NOT NULL,
    response_hash VARCHAR(64) NOT NULL,
    checked_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_eligibility_check_application FOREIGN KEY (application_id) REFERENCES loan_applications (id),
    CONSTRAINT ck_eligibility_check_age CHECK (age IS NULL OR age BETWEEN 0 AND 120),
    CONSTRAINT ck_eligibility_check_kyc CHECK (kyc_status IN ('VERIFIED', 'PENDING', 'PROCESSING', 'REJECTED', 'EXPIRED')),
    CONSTRAINT ck_eligibility_check_income CHECK (income_verification_status IN ('VERIFIED', 'SOURCE_VERIFIED', 'NOT_VERIFIED')),
    CONSTRAINT ck_eligibility_check_source CHECK (profile_source IN ('MOCK_USER_PROFILE', 'USER_SERVICE')),
    CONSTRAINT ck_eligibility_check_result CHECK (eligibility_result IN (
        'ELIGIBLE', 'RETRY_PENDING', 'INELIGIBLE', 'DEPENDENCY_UNAVAILABLE', 'INVALID_PROFILE'
    ))
);

CREATE TABLE borrower_credit_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrower_id VARCHAR(100) NOT NULL UNIQUE,
    has_internal_credit_history BOOLEAN NOT NULL,
    internal_delinquencies_last_2_years INTEGER NOT NULL,
    internal_defaulted_loan_count INTEGER NOT NULL,
    completed_loan_count INTEGER NOT NULL,
    on_time_payment_rate NUMERIC(7, 4),
    source VARCHAR(30) NOT NULL,
    calculation_policy_version VARCHAR(50) NOT NULL,
    source_event_id VARCHAR(100),
    source_event_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_credit_profile_counts CHECK (
        internal_delinquencies_last_2_years >= 0
        AND internal_defaulted_loan_count >= 0
        AND completed_loan_count >= 0
    ),
    CONSTRAINT ck_credit_profile_rate CHECK (on_time_payment_rate IS NULL OR on_time_payment_rate BETWEEN 0 AND 1),
    CONSTRAINT ck_credit_profile_source CHECK (source IN ('NO_HISTORY', 'FINERACT_INTERNAL'))
);

CREATE TABLE credit_scoring_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    eligibility_check_id BIGINT NOT NULL,
    request_id VARCHAR(100) NOT NULL UNIQUE,
    logical_scoring_key VARCHAR(150) NOT NULL UNIQUE,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    requested_model_version VARCHAR(30) NOT NULL,
    actual_model_version VARCHAR(30),
    input_snapshot_json JSONB NOT NULL,
    input_source_snapshot_json JSONB NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    pd_probability NUMERIC(10, 8),
    risk_score INTEGER,
    evaluation_score NUMERIC(9, 4),
    credit_grade VARCHAR(5),
    suggested_limit NUMERIC(18, 2),
    ai_recommendation VARCHAR(30),
    rejection_reason VARCHAR(1000),
    response_snapshot_json JSONB,
    response_hash VARCHAR(64),
    decision_policy_version VARCHAR(50),
    failure_code VARCHAR(100),
    failure_detail VARCHAR(1000),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    scored_at TIMESTAMPTZ,
    next_retry_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_credit_assessment_application FOREIGN KEY (application_id) REFERENCES loan_applications (id),
    CONSTRAINT fk_credit_assessment_eligibility FOREIGN KEY (eligibility_check_id) REFERENCES borrower_eligibility_checks (id),
    CONSTRAINT ck_credit_assessment_attempt CHECK (attempt_count >= 0),
    CONSTRAINT ck_credit_assessment_status CHECK (status IN ('PENDING', 'PROCESSING', 'RETRY_PENDING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_credit_assessment_probability CHECK (pd_probability IS NULL OR pd_probability BETWEEN 0 AND 1),
    CONSTRAINT ck_credit_assessment_risk_score CHECK (risk_score IS NULL OR risk_score BETWEEN 0 AND 100),
    CONSTRAINT ck_credit_assessment_grade CHECK (credit_grade IS NULL OR credit_grade IN ('A', 'B', 'C', 'D')),
    CONSTRAINT ck_credit_assessment_recommendation CHECK (
        ai_recommendation IS NULL OR ai_recommendation IN ('APPROVED', 'PENDING_REVIEW', 'REJECTED')
    )
);

CREATE TABLE credit_scoring_retry_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    assessment_id BIGINT NOT NULL,
    idempotency_key VARCHAR(150) NOT NULL UNIQUE,
    request_hash VARCHAR(64) NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_scoring_retry_application FOREIGN KEY (application_id) REFERENCES loan_applications (id),
    CONSTRAINT fk_scoring_retry_assessment FOREIGN KEY (assessment_id) REFERENCES credit_scoring_assessments (id)
);

ALTER TABLE loan_applications
    ADD COLUMN latest_credit_assessment_id BIGINT;

ALTER TABLE loan_applications
    ADD CONSTRAINT fk_loan_application_latest_assessment
    FOREIGN KEY (latest_credit_assessment_id) REFERENCES credit_scoring_assessments (id);

ALTER TABLE loan_applications DROP CONSTRAINT ck_loan_application_status;
ALTER TABLE loan_applications ADD CONSTRAINT ck_loan_application_status CHECK (status IN (
    'SUBMITTED', 'ELIGIBILITY_PENDING', 'SCORING', 'SCORING_RETRY_PENDING',
    'PENDING_REVIEW', 'REJECTED', 'WITHDRAWN'
));

ALTER TABLE loan_application_status_histories DROP CONSTRAINT ck_application_history_from_status;
ALTER TABLE loan_application_status_histories ADD CONSTRAINT ck_application_history_from_status CHECK (
    from_status IS NULL OR from_status IN (
        'SUBMITTED', 'ELIGIBILITY_PENDING', 'SCORING', 'SCORING_RETRY_PENDING',
        'PENDING_REVIEW', 'REJECTED', 'WITHDRAWN'
    )
);

ALTER TABLE loan_application_status_histories DROP CONSTRAINT ck_application_history_to_status;
ALTER TABLE loan_application_status_histories ADD CONSTRAINT ck_application_history_to_status CHECK (to_status IN (
    'SUBMITTED', 'ELIGIBILITY_PENDING', 'SCORING', 'SCORING_RETRY_PENDING',
    'PENDING_REVIEW', 'REJECTED', 'WITHDRAWN'
));

-- Các index dưới đây bám đúng worker, timeline và màn hình review; không index JSON snapshot bất biến.
CREATE INDEX idx_eligibility_checks_application_created
    ON borrower_eligibility_checks (application_id, created_at DESC, id DESC);
CREATE INDEX idx_credit_assessments_application_created
    ON credit_scoring_assessments (application_id, created_at DESC, id DESC);
CREATE INDEX idx_credit_assessments_retry
    ON credit_scoring_assessments (status, next_retry_at, updated_at, id);
CREATE INDEX idx_scoring_retry_requests_assessment
    ON credit_scoring_retry_requests (assessment_id, created_at DESC, id DESC);
