ALTER TABLE loan_applications
    ADD COLUMN admin_decision_reason_code VARCHAR(50),
    ADD COLUMN admin_decision_reason_detail VARCHAR(1000),
    ADD COLUMN admin_decision_policy_version VARCHAR(30),
    ADD COLUMN admin_decision_assessment_id BIGINT,
    ADD COLUMN admin_decision_idempotency_key VARCHAR(150),
    ADD COLUMN admin_decision_request_hash VARCHAR(64),
    ADD COLUMN admin_decided_by VARCHAR(100),
    ADD COLUMN admin_decided_at TIMESTAMPTZ;

ALTER TABLE loan_applications
    ADD CONSTRAINT fk_loan_application_admin_decision_assessment
    FOREIGN KEY (admin_decision_assessment_id) REFERENCES credit_scoring_assessments (id);

CREATE UNIQUE INDEX uq_loan_applications_admin_decision_idempotency
    ON loan_applications (admin_decision_idempotency_key)
    WHERE admin_decision_idempotency_key IS NOT NULL;

ALTER TABLE loan_applications DROP CONSTRAINT ck_loan_application_status;
ALTER TABLE loan_applications ADD CONSTRAINT ck_loan_application_status CHECK (status IN (
    'SUBMITTED', 'ELIGIBILITY_PENDING', 'SCORING', 'SCORING_RETRY_PENDING',
    'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'WITHDRAWN'
));

ALTER TABLE loan_application_status_histories DROP CONSTRAINT ck_application_history_from_status;
ALTER TABLE loan_application_status_histories ADD CONSTRAINT ck_application_history_from_status CHECK (
    from_status IS NULL OR from_status IN (
        'SUBMITTED', 'ELIGIBILITY_PENDING', 'SCORING', 'SCORING_RETRY_PENDING',
        'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'WITHDRAWN'
    )
);

ALTER TABLE loan_application_status_histories DROP CONSTRAINT ck_application_history_to_status;
ALTER TABLE loan_application_status_histories ADD CONSTRAINT ck_application_history_to_status CHECK (to_status IN (
    'SUBMITTED', 'ELIGIBILITY_PENDING', 'SCORING', 'SCORING_RETRY_PENDING',
    'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'WITHDRAWN'
));

ALTER TABLE loan_applications ADD CONSTRAINT ck_loan_application_admin_decision_evidence CHECK (
    (
        admin_decision_reason_code IS NULL
        AND admin_decision_reason_detail IS NULL
        AND admin_decision_policy_version IS NULL
        AND admin_decision_assessment_id IS NULL
        AND admin_decision_idempotency_key IS NULL
        AND admin_decision_request_hash IS NULL
        AND admin_decided_by IS NULL
        AND admin_decided_at IS NULL
    )
    OR
    (
        status IN ('APPROVED', 'REJECTED')
        AND admin_decision_reason_code IS NOT NULL
        AND admin_decision_policy_version IS NOT NULL
        AND admin_decision_idempotency_key IS NOT NULL
        AND admin_decision_request_hash IS NOT NULL
        AND admin_decided_by IS NOT NULL
        AND admin_decided_at IS NOT NULL
    )
);

ALTER TABLE loan_applications ADD CONSTRAINT ck_loan_application_approved_assessment CHECK (
    status <> 'APPROVED' OR admin_decision_assessment_id IS NOT NULL
);

CREATE TABLE loan_contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_number VARCHAR(50) NOT NULL,
    application_id BIGINT NOT NULL,
    borrower_id VARCHAR(100) NOT NULL,
    principal_amount NUMERIC(18, 2) NOT NULL,
    term_months SMALLINT NOT NULL,
    annual_interest_rate NUMERIC(7, 4) NOT NULL,
    repayment_method VARCHAR(30) NOT NULL,
    calculation_snapshot_id BIGINT NOT NULL,
    total_interest NUMERIC(18, 2) NOT NULL,
    total_fees NUMERIC(18, 2) NOT NULL,
    total_penalties NUMERIC(18, 2) NOT NULL,
    total_repayment NUMERIC(18, 2) NOT NULL,
    first_installment NUMERIC(18, 2) NOT NULL,
    maximum_installment NUMERIC(18, 2) NOT NULL,
    schedule_response_hash VARCHAR(64) NOT NULL,
    expected_disbursement_date DATE NOT NULL,
    terms_version VARCHAR(30) NOT NULL,
    document_version VARCHAR(30) NOT NULL,
    document_content TEXT NOT NULL,
    document_content_type VARCHAR(50) NOT NULL,
    document_hash VARCHAR(64) NOT NULL,
    status VARCHAR(30) NOT NULL,
    consent_idempotency_key VARCHAR(150),
    consent_request_hash VARCHAR(64),
    consent_action VARCHAR(20),
    signed_by VARCHAR(100),
    signed_at TIMESTAMPTZ,
    signature_method VARCHAR(30),
    declined_by VARCHAR(100),
    declined_at TIMESTAMPTZ,
    decline_reason_code VARCHAR(50),
    decline_reason_detail VARCHAR(1000),
    expires_at TIMESTAMPTZ NOT NULL,
    effective_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL,
    updated_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_loan_contracts_contract_number UNIQUE (contract_number),
    CONSTRAINT uq_loan_contracts_application UNIQUE (application_id),
    CONSTRAINT fk_loan_contract_application FOREIGN KEY (application_id) REFERENCES loan_applications (id),
    CONSTRAINT fk_loan_contract_calculation FOREIGN KEY (calculation_snapshot_id) REFERENCES schedule_calculation_snapshots (id),
    CONSTRAINT ck_loan_contract_principal CHECK (principal_amount > 0),
    CONSTRAINT ck_loan_contract_term CHECK (term_months > 0),
    CONSTRAINT ck_loan_contract_rate CHECK (annual_interest_rate > 0 AND annual_interest_rate <= 100),
    CONSTRAINT ck_loan_contract_totals CHECK (
        total_interest >= 0 AND total_fees >= 0 AND total_penalties >= 0
        AND total_repayment >= principal_amount AND first_installment >= 0 AND maximum_installment >= 0
    ),
    CONSTRAINT ck_loan_contract_repayment CHECK (repayment_method IN ('ANNUITY', 'EQUAL_PRINCIPAL')),
    CONSTRAINT ck_loan_contract_status CHECK (status IN (
        'PENDING_SIGNATURE', 'SIGNED', 'DECLINED', 'EXPIRED', 'EFFECTIVE', 'COMPLETED'
    )),
    CONSTRAINT ck_loan_contract_hashes CHECK (
        length(schedule_response_hash) = 64 AND length(document_hash) = 64
    ),
    CONSTRAINT ck_loan_contract_document CHECK (
        length(document_content) > 0 AND document_content_type = 'text/plain; charset=UTF-8'
    ),
    CONSTRAINT ck_loan_contract_expiry CHECK (expires_at > created_at),
    CONSTRAINT ck_loan_contract_consent CHECK (
        (
            status IN ('PENDING_SIGNATURE', 'EXPIRED')
            AND consent_idempotency_key IS NULL AND consent_request_hash IS NULL AND consent_action IS NULL
            AND signed_by IS NULL AND signed_at IS NULL AND signature_method IS NULL
            AND declined_by IS NULL AND declined_at IS NULL AND decline_reason_code IS NULL
        )
        OR
        (
            status IN ('SIGNED', 'EFFECTIVE', 'COMPLETED')
            AND consent_idempotency_key IS NOT NULL AND consent_request_hash IS NOT NULL
            AND consent_action = 'SIGN'
            AND signed_by IS NOT NULL AND signed_at IS NOT NULL AND signature_method = 'CLICK_WRAP_MVP'
            AND declined_by IS NULL AND declined_at IS NULL AND decline_reason_code IS NULL
        )
        OR
        (
            status = 'DECLINED'
            AND consent_idempotency_key IS NOT NULL AND consent_request_hash IS NOT NULL
            AND consent_action = 'DECLINE'
            AND signed_by IS NULL AND signed_at IS NULL AND signature_method IS NULL
            AND declined_by IS NOT NULL AND declined_at IS NOT NULL AND decline_reason_code IS NOT NULL
        )
    )
);

CREATE UNIQUE INDEX uq_loan_contracts_consent_idempotency
    ON loan_contracts (consent_idempotency_key)
    WHERE consent_idempotency_key IS NOT NULL;

CREATE TABLE loan_contract_status_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    from_status VARCHAR(30),
    to_status VARCHAR(30) NOT NULL,
    reason_code VARCHAR(50),
    actor_type VARCHAR(20) NOT NULL,
    actor_id VARCHAR(100) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    trace_id VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_contract_history_contract FOREIGN KEY (contract_id) REFERENCES loan_contracts (id),
    CONSTRAINT ck_contract_history_from_status CHECK (
        from_status IS NULL OR from_status IN (
            'PENDING_SIGNATURE', 'SIGNED', 'DECLINED', 'EXPIRED', 'EFFECTIVE', 'COMPLETED'
        )
    ),
    CONSTRAINT ck_contract_history_to_status CHECK (to_status IN (
        'PENDING_SIGNATURE', 'SIGNED', 'DECLINED', 'EXPIRED', 'EFFECTIVE', 'COMPLETED'
    )),
    CONSTRAINT ck_contract_history_actor CHECK (actor_type IN ('BORROWER', 'ADMIN', 'SYSTEM'))
);

CREATE INDEX idx_loan_applications_pending_review
    ON loan_applications (created_at DESC, id DESC) WHERE status = 'PENDING_REVIEW';
CREATE INDEX idx_loan_contracts_borrower_created
    ON loan_contracts (borrower_id, created_at DESC, id DESC);
CREATE INDEX idx_loan_contracts_pending_expiry
    ON loan_contracts (expires_at, id) WHERE status = 'PENDING_SIGNATURE';
CREATE INDEX idx_loan_contract_histories_timeline
    ON loan_contract_status_histories (contract_id, occurred_at DESC, id DESC);
