CREATE TABLE loan_contract_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    artifact_type VARCHAR(30) NOT NULL,
    document_version VARCHAR(30) NOT NULL,
    content_type VARCHAR(50) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    content_length INTEGER NOT NULL,
    content BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_loan_contract_document_contract
        FOREIGN KEY (contract_id) REFERENCES loan_contracts (id),
    CONSTRAINT uq_loan_contract_document_type UNIQUE (contract_id, artifact_type),
    CONSTRAINT ck_loan_contract_document_type CHECK (
        artifact_type IN ('SIGNABLE', 'SIGNED_RECEIPT')
    ),
    CONSTRAINT ck_loan_contract_document_content CHECK (
        content_type = 'application/pdf'
        AND length(content_hash) = 64
        AND content_length > 0
        AND octet_length(content) = content_length
    )
);

CREATE INDEX idx_loan_contract_documents_contract_created
    ON loan_contract_documents (contract_id, created_at DESC, id DESC);
