spring:
  application:
    name: finora-investment
  data:
    mongodb:
      uri: mongodb://localhost:27017/finora_investment
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8084
