spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: finora-blockchain
  datasource:
    url: ${BLOCKCHAIN_DB_URL:jdbc:postgresql://localhost:15435/finora_blockchain}
    username: ${BLOCKCHAIN_DB_USERNAME:finora_blockchain}
    password: ${BLOCKCHAIN_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: blockchain-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8083

# Hyperledger Fabric
fabric:
  channel-name: finora-channel
  chaincode-name: finora-ledger
  msp-id: Org1MSP
  # Các path này sẽ được cấu hình khi dựng mạng Fabric
  cert-path: ${FABRIC_CERT_PATH:./fabric-config/cert.pem}
  key-path: ${FABRIC_KEY_PATH:./fabric-config/key.pem}
  tls-cert-path: ${FABRIC_TLS_CERT_PATH:./fabric-config/tls-cert.pem}
  peer-endpoint: ${FABRIC_PEER_ENDPOINT:localhost:7051}
