CREATE TABLE blockchain_proof_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proof_id UUID NOT NULL,
    source_service VARCHAR(50) NOT NULL,
    source_event_id UUID NOT NULL,
    aggregate_type VARCHAR(50) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    proof_type VARCHAR(50) NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    payload_version INTEGER NOT NULL,
    provider VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMP WITH TIME ZONE NOT NULL,
    processing_started_at TIMESTAMP WITH TIME ZONE,
    processing_token UUID,
    provider_transaction_id VARCHAR(200),
    provider_block_reference VARCHAR(200),
    confirmed_at TIMESTAMP WITH TIME ZONE,
    last_error_code VARCHAR(60),
    last_error_detail VARCHAR(500),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_blockchain_proof_submissions_proof_id UNIQUE (proof_id),
    CONSTRAINT uq_blockchain_proof_submissions_source_event UNIQUE (source_service, source_event_id),
    CONSTRAINT ck_blockchain_proof_submissions_source_service
        CHECK (source_service ~ '^finora-[a-z0-9-]+$'),
    CONSTRAINT ck_blockchain_proof_submissions_payload_hash
        CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_blockchain_proof_submissions_payload_version CHECK (payload_version > 0),
    CONSTRAINT ck_blockchain_proof_submissions_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT ck_blockchain_proof_submissions_provider
        CHECK (provider IN ('MOCK', 'HYPERLEDGER_FABRIC')),
    CONSTRAINT ck_blockchain_proof_submissions_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'CONFIRMED', 'DEAD_LETTER')),
    CONSTRAINT ck_blockchain_proof_submissions_confirmed
        CHECK (
            (status = 'CONFIRMED'
                AND provider_transaction_id IS NOT NULL
                AND confirmed_at IS NOT NULL)
            OR (status <> 'CONFIRMED'
                AND provider_transaction_id IS NULL
                AND confirmed_at IS NULL)
        ),
    CONSTRAINT ck_blockchain_proof_submissions_processing
        CHECK (
            (status = 'PROCESSING'
                AND processing_started_at IS NOT NULL
                AND processing_token IS NOT NULL)
            OR (status <> 'PROCESSING'
                AND processing_started_at IS NULL
                AND processing_token IS NULL)
        )
);

CREATE UNIQUE INDEX uq_blockchain_proof_submissions_provider_transaction
    ON blockchain_proof_submissions (provider, provider_transaction_id)
    WHERE provider_transaction_id IS NOT NULL;

CREATE INDEX idx_blockchain_proof_submissions_due
    ON blockchain_proof_submissions (available_at, id)
    WHERE status = 'PENDING';

CREATE INDEX idx_blockchain_proof_submissions_processing_lease
    ON blockchain_proof_submissions (processing_started_at, id)
    WHERE status = 'PROCESSING';

CREATE INDEX idx_blockchain_proof_submissions_aggregate
    ON blockchain_proof_submissions (aggregate_type, aggregate_id, created_at, id);
