CREATE TABLE payment_wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id UUID NOT NULL,
    owner_type VARCHAR(30) NOT NULL,
    owner_id VARCHAR(100) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    available_balance NUMERIC(19, 2) NOT NULL DEFAULT 0,
    held_balance NUMERIC(19, 2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_payment_wallets_wallet_id UNIQUE (wallet_id),
    CONSTRAINT uq_payment_wallets_owner_currency UNIQUE (owner_type, owner_id, currency),
    CONSTRAINT ck_payment_wallets_owner_type CHECK (owner_type IN ('BORROWER', 'INVESTOR', 'PLATFORM')),
    CONSTRAINT ck_payment_wallets_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_payment_wallets_available_non_negative CHECK (available_balance >= 0),
    CONSTRAINT ck_payment_wallets_held_non_negative CHECK (held_balance >= 0),
    CONSTRAINT ck_payment_wallets_status CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED'))
);

CREATE TABLE payment_ledger_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id UUID NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    transaction_type VARCHAR(30) NOT NULL,
    reference_type VARCHAR(50) NOT NULL,
    reference_id VARCHAR(100) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    posted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_payment_ledger_transactions_transaction_id UNIQUE (transaction_id),
    CONSTRAINT uq_payment_ledger_transactions_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_payment_ledger_transactions_request_hash CHECK (request_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_payment_ledger_transactions_type CHECK (transaction_type IN (
        'DEPOSIT', 'WITHDRAWAL', 'HOLD', 'RELEASE', 'CAPTURE',
        'DISBURSEMENT', 'REPAYMENT', 'DISTRIBUTION', 'ADJUSTMENT'
    )),
    CONSTRAINT ck_payment_ledger_transactions_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_payment_ledger_transactions_amount CHECK (total_amount > 0),
    CONSTRAINT ck_payment_ledger_transactions_status CHECK (status IN ('PROCESSING', 'POSTED')),
    CONSTRAINT ck_payment_ledger_transactions_posted CHECK (
        (status = 'POSTED' AND posted_at IS NOT NULL)
        OR (status = 'PROCESSING' AND posted_at IS NULL)
    )
);

CREATE TABLE payment_ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL,
    entry_sequence INTEGER NOT NULL,
    wallet_id BIGINT,
    account_code VARCHAR(150) NOT NULL,
    balance_bucket VARCHAR(20) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_payment_ledger_entries_transaction
        FOREIGN KEY (transaction_id) REFERENCES payment_ledger_transactions(id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_ledger_entries_wallet
        FOREIGN KEY (wallet_id) REFERENCES payment_wallets(id) ON DELETE RESTRICT,
    CONSTRAINT uq_payment_ledger_entries_sequence UNIQUE (transaction_id, entry_sequence),
    CONSTRAINT ck_payment_ledger_entries_account_code CHECK (account_code ~ '^[A-Z0-9:_-]+$'),
    CONSTRAINT ck_payment_ledger_entries_bucket CHECK (balance_bucket IN ('AVAILABLE', 'HELD', 'CLEARING')),
    CONSTRAINT ck_payment_ledger_entries_direction CHECK (direction IN ('DEBIT', 'CREDIT')),
    CONSTRAINT ck_payment_ledger_entries_amount CHECK (amount > 0),
    CONSTRAINT ck_payment_ledger_entries_wallet_bucket CHECK (
        (balance_bucket = 'CLEARING' AND wallet_id IS NULL)
        OR (balance_bucket IN ('AVAILABLE', 'HELD') AND wallet_id IS NOT NULL)
    )
);

CREATE INDEX idx_payment_ledger_transactions_reference
    ON payment_ledger_transactions (reference_type, reference_id, created_at, id);

CREATE INDEX idx_payment_ledger_entries_wallet_statement
    ON payment_ledger_entries (wallet_id, created_at, id)
    WHERE wallet_id IS NOT NULL;

CREATE OR REPLACE FUNCTION reject_payment_ledger_entry_mutation()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'payment ledger entries are append-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_payment_ledger_entries_immutable
BEFORE UPDATE OR DELETE ON payment_ledger_entries
FOR EACH ROW EXECUTE FUNCTION reject_payment_ledger_entry_mutation();

CREATE OR REPLACE FUNCTION protect_payment_ledger_transaction()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'payment ledger transactions cannot be deleted';
    END IF;
    IF OLD.status = 'POSTED' THEN
        RAISE EXCEPTION 'posted payment ledger transactions are immutable';
    END IF;
    IF NEW.status <> 'POSTED'
       OR NEW.transaction_id IS DISTINCT FROM OLD.transaction_id
       OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
       OR NEW.request_hash IS DISTINCT FROM OLD.request_hash
       OR NEW.transaction_type IS DISTINCT FROM OLD.transaction_type
       OR NEW.reference_type IS DISTINCT FROM OLD.reference_type
       OR NEW.reference_id IS DISTINCT FROM OLD.reference_id
       OR NEW.currency IS DISTINCT FROM OLD.currency
       OR NEW.total_amount IS DISTINCT FROM OLD.total_amount
       OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'only PROCESSING to POSTED transition is allowed';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_payment_ledger_transactions_immutable
BEFORE UPDATE OR DELETE ON payment_ledger_transactions
FOR EACH ROW EXECUTE FUNCTION protect_payment_ledger_transaction();
