CREATE TABLE payment_disbursements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saga_id UUID NOT NULL,
    loan_application_id BIGINT NOT NULL,
    contract_number VARCHAR(50) NOT NULL,
    listing_id BIGINT NOT NULL,
    borrower_id VARCHAR(100) NOT NULL,
    amount NUMERIC(18, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(30) NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_reference VARCHAR(100),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ,
    error_code VARCHAR(80),
    error_detail VARCHAR(500),
    completed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_payment_disbursement_saga UNIQUE (saga_id),
    CONSTRAINT uq_payment_disbursement_provider_reference UNIQUE (provider_reference),
    CONSTRAINT ck_payment_disbursement_amount CHECK (amount > 0),
    CONSTRAINT ck_payment_disbursement_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_payment_disbursement_status CHECK (status IN ('REQUESTED','PROCESSING','RETRY_PENDING','COMPLETED','FAILED'))
);

CREATE INDEX idx_payment_disbursement_due ON payment_disbursements (next_attempt_at, id)
    WHERE status IN ('REQUESTED','RETRY_PENDING');

CREATE TABLE payment_processed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    event_type VARCHAR(100) NOT NULL,
    aggregate_id VARCHAR(100) NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE payment_outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    aggregate_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_version INTEGER NOT NULL,
    payload_json JSONB NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ,
    last_error VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_payment_outbox_status CHECK (status IN ('PENDING','PUBLISHED','DEAD_LETTER'))
);

CREATE INDEX idx_payment_outbox_due ON payment_outbox_events (available_at, id) WHERE status = 'PENDING';

