CREATE TABLE payment_top_ups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    top_up_id UUID NOT NULL,
    wallet_id BIGINT NOT NULL,
    owner_id VARCHAR(100) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    provider VARCHAR(30) NOT NULL,
    provider_order_id VARCHAR(100) NOT NULL,
    provider_reference VARCHAR(100),
    checkout_url TEXT,
    qr_payload TEXT,
    status VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(150) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    error_code VARCHAR(80),
    error_detail VARCHAR(500),
    expires_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_payment_top_ups_wallet
        FOREIGN KEY (wallet_id) REFERENCES payment_wallets(id) ON DELETE RESTRICT,
    CONSTRAINT uq_payment_top_ups_public_id UNIQUE (top_up_id),
    CONSTRAINT uq_payment_top_ups_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uq_payment_top_ups_provider_order UNIQUE (provider, provider_order_id),
    CONSTRAINT uq_payment_top_ups_provider_reference UNIQUE (provider, provider_reference),
    CONSTRAINT ck_payment_top_ups_amount CHECK (amount > 0),
    CONSTRAINT ck_payment_top_ups_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_payment_top_ups_status CHECK (status IN (
        'PROVIDER_PENDING', 'AWAITING_PAYMENT', 'COMPLETED', 'FAILED',
        'EXPIRED', 'RECONCILIATION_REQUIRED'
    )),
    CONSTRAINT ck_payment_top_ups_request_hash CHECK (request_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_payment_top_ups_owner_created
    ON payment_top_ups (owner_id, created_at DESC, id DESC);

CREATE INDEX idx_payment_top_ups_pending
    ON payment_top_ups (status, expires_at, id)
    WHERE status IN ('PROVIDER_PENDING', 'AWAITING_PAYMENT', 'RECONCILIATION_REQUIRED');

CREATE TABLE payment_holds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hold_id UUID NOT NULL,
    hold_reference VARCHAR(100) NOT NULL,
    order_reference VARCHAR(100) NOT NULL,
    wallet_id BIGINT NOT NULL,
    owner_id VARCHAR(100) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(30) NOT NULL,
    capture_reference VARCHAR(100),
    held_at TIMESTAMPTZ NOT NULL,
    released_at TIMESTAMPTZ,
    captured_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_payment_holds_wallet
        FOREIGN KEY (wallet_id) REFERENCES payment_wallets(id) ON DELETE RESTRICT,
    CONSTRAINT uq_payment_holds_public_id UNIQUE (hold_id),
    CONSTRAINT uq_payment_holds_reference UNIQUE (hold_reference),
    CONSTRAINT uq_payment_holds_order UNIQUE (order_reference),
    CONSTRAINT ck_payment_holds_amount CHECK (amount > 0),
    CONSTRAINT ck_payment_holds_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_payment_holds_status CHECK (status IN (
        'HELD', 'CAPTURE_PENDING', 'CAPTURED', 'RELEASED'
    ))
);

CREATE INDEX idx_payment_holds_wallet_status
    ON payment_holds (wallet_id, status, id);

ALTER TABLE payment_disbursements
    ADD COLUMN allocation_snapshot_json JSONB,
    ADD COLUMN ledger_transaction_id UUID;

ALTER TABLE payment_disbursements
    DROP CONSTRAINT ck_payment_disbursement_status,
    ADD CONSTRAINT ck_payment_disbursement_status CHECK (status IN (
        'REQUESTED', 'PROCESSING', 'RETRY_PENDING', 'COMPLETED', 'FAILED',
        'RECONCILIATION_REQUIRED'
    ));
