CREATE TABLE payment_loan_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_application_id BIGINT NOT NULL,
    contract_number VARCHAR(50) NOT NULL,
    listing_id BIGINT NOT NULL,
    borrower_id VARCHAR(100) NOT NULL,
    fineract_loan_id BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(20) NOT NULL,
    activated_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_payment_loan_accounts_application UNIQUE (loan_application_id),
    CONSTRAINT uq_payment_loan_accounts_contract UNIQUE (contract_number),
    CONSTRAINT uq_payment_loan_accounts_fineract UNIQUE (fineract_loan_id),
    CONSTRAINT ck_payment_loan_accounts_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_payment_loan_accounts_status CHECK (status IN ('ACTIVE','CLOSED'))
);

CREATE INDEX idx_payment_loan_accounts_borrower
    ON payment_loan_accounts (borrower_id, status, id DESC);

CREATE TABLE payment_note_ownership (
    note_id BIGINT PRIMARY KEY,
    note_number VARCHAR(50) NOT NULL,
    loan_application_id BIGINT NOT NULL,
    listing_id BIGINT NOT NULL,
    investor_id VARCHAR(100) NOT NULL,
    outstanding_principal NUMERIC(18,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    ownership_changed_at TIMESTAMPTZ NOT NULL,
    source_reference VARCHAR(100) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_payment_note_ownership_number UNIQUE (note_number),
    CONSTRAINT ck_payment_note_ownership_outstanding CHECK (outstanding_principal >= 0),
    CONSTRAINT ck_payment_note_ownership_currency CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE INDEX idx_payment_note_ownership_loan
    ON payment_note_ownership (loan_application_id, note_id);

CREATE TABLE payment_repayments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repayment_id UUID NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    loan_application_id BIGINT NOT NULL,
    borrower_id VARCHAR(100) NOT NULL,
    fineract_loan_id BIGINT NOT NULL,
    amount NUMERIC(18,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    transaction_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    wallet_ledger_transaction_id UUID NOT NULL,
    distribution_ledger_transaction_id UUID,
    fineract_transaction_id BIGINT,
    principal_amount NUMERIC(18,2),
    interest_amount NUMERIC(18,2),
    fee_amount NUMERIC(18,2),
    penalty_amount NUMERIC(18,2),
    outstanding_principal NUMERIC(18,2),
    next_due_date DATE,
    next_due_amount NUMERIC(18,2),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    error_code VARCHAR(80),
    error_detail VARCHAR(500),
    completed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_payment_repayments_id UNIQUE (repayment_id),
    CONSTRAINT uq_payment_repayments_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uq_payment_repayments_fineract_transaction UNIQUE (fineract_transaction_id),
    CONSTRAINT ck_payment_repayments_amount CHECK (amount > 0),
    CONSTRAINT ck_payment_repayments_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_payment_repayments_status CHECK (status IN (
        'COLLECTED','CORE_POSTING','CORE_POSTED','COMPLETED','RECONCILIATION_REQUIRED','FAILED'
    )),
    CONSTRAINT ck_payment_repayments_breakdown CHECK (
        (principal_amount IS NULL AND interest_amount IS NULL AND fee_amount IS NULL AND penalty_amount IS NULL)
        OR (principal_amount >= 0 AND interest_amount >= 0 AND fee_amount >= 0 AND penalty_amount >= 0
            AND principal_amount + interest_amount + fee_amount + penalty_amount = amount)
    )
);

CREATE INDEX idx_payment_repayments_due
    ON payment_repayments (status, created_at, id)
    WHERE status = 'COLLECTED';

CREATE INDEX idx_payment_repayments_borrower
    ON payment_repayments (borrower_id, created_at DESC, id DESC);
