CREATE TABLE payment_early_settlement_quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id UUID NOT NULL,
    loan_application_id BIGINT NOT NULL,
    borrower_id VARCHAR(100) NOT NULL,
    fineract_loan_id BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    transaction_date DATE NOT NULL,
    principal_portion NUMERIC(18,2) NOT NULL,
    interest_portion NUMERIC(18,2) NOT NULL,
    core_fee_portion NUMERIC(18,2) NOT NULL,
    penalty_portion NUMERIC(18,2) NOT NULL,
    core_amount NUMERIC(18,2) NOT NULL,
    platform_fee NUMERIC(18,2) NOT NULL,
    total_amount NUMERIC(18,2) NOT NULL,
    fee_rate NUMERIC(7,6) NOT NULL,
    policy_version VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_payment_early_settlement_quotes_id UNIQUE (quote_id),
    CONSTRAINT ck_payment_early_settlement_quotes_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_payment_early_settlement_quotes_amounts CHECK (
        principal_portion >= 0 AND interest_portion >= 0 AND core_fee_portion >= 0
        AND penalty_portion >= 0 AND platform_fee >= 0 AND core_amount > 0
        AND principal_portion + interest_portion + core_fee_portion + penalty_portion = core_amount
        AND core_amount + platform_fee = total_amount
    ),
    CONSTRAINT ck_payment_early_settlement_quotes_rate CHECK (fee_rate >= 0 AND fee_rate <= 1),
    CONSTRAINT ck_payment_early_settlement_quotes_status CHECK (status IN ('ACTIVE','CONSUMED','EXPIRED'))
);

CREATE INDEX idx_payment_early_settlement_quotes_borrower
    ON payment_early_settlement_quotes (borrower_id, created_at DESC, id DESC);

ALTER TABLE payment_repayments
    ADD COLUMN repayment_type VARCHAR(30) NOT NULL DEFAULT 'SCHEDULED',
    ADD COLUMN quote_id UUID,
    ADD COLUMN core_amount NUMERIC(18,2),
    ADD COLUMN platform_fee NUMERIC(18,2) NOT NULL DEFAULT 0;

UPDATE payment_repayments SET core_amount = amount WHERE core_amount IS NULL;

ALTER TABLE payment_repayments
    ALTER COLUMN core_amount SET NOT NULL,
    ADD CONSTRAINT fk_payment_repayments_quote
        FOREIGN KEY (quote_id) REFERENCES payment_early_settlement_quotes(quote_id) ON DELETE RESTRICT,
    ADD CONSTRAINT uq_payment_repayments_quote UNIQUE (quote_id),
    ADD CONSTRAINT ck_payment_repayments_type CHECK (repayment_type IN ('SCHEDULED','EARLY_SETTLEMENT')),
    ADD CONSTRAINT ck_payment_repayments_core_amount CHECK (
        core_amount > 0 AND platform_fee >= 0 AND core_amount + platform_fee = amount
    );
