ALTER TABLE payment_loan_accounts
    ADD COLUMN core_config_version VARCHAR(50) NOT NULL DEFAULT 'FINORA-FINERACT-V1';

CREATE TABLE payment_partial_prepayment_quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id UUID NOT NULL,
    loan_application_id BIGINT NOT NULL,
    borrower_id VARCHAR(100) NOT NULL,
    fineract_loan_id BIGINT NOT NULL,
    core_config_version VARCHAR(50) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    transaction_date DATE NOT NULL,
    scheduled_due NUMERIC(18,2) NOT NULL,
    prepaid_principal NUMERIC(18,2) NOT NULL,
    core_amount NUMERIC(18,2) NOT NULL,
    platform_fee NUMERIC(18,2) NOT NULL,
    total_amount NUMERIC(18,2) NOT NULL,
    outstanding_principal_before NUMERIC(18,2) NOT NULL,
    next_due_date_before DATE,
    next_due_amount_before NUMERIC(18,2) NOT NULL,
    fee_rate NUMERIC(7,6) NOT NULL,
    policy_version VARCHAR(50) NOT NULL,
    allocation_strategy VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_payment_partial_prepayment_quotes_id UNIQUE (quote_id),
    CONSTRAINT ck_payment_partial_prepayment_quotes_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_payment_partial_prepayment_quotes_amounts CHECK (
        scheduled_due >= 0 AND prepaid_principal > 0
        AND core_amount = scheduled_due + prepaid_principal
        AND platform_fee >= 0 AND total_amount = core_amount + platform_fee
        AND outstanding_principal_before > prepaid_principal AND next_due_amount_before >= 0
    ),
    CONSTRAINT ck_payment_partial_prepayment_quotes_rate CHECK (fee_rate >= 0 AND fee_rate <= 1),
    CONSTRAINT ck_payment_partial_prepayment_quotes_status CHECK (status IN ('ACTIVE','CONSUMED','EXPIRED'))
);

CREATE INDEX idx_payment_partial_prepayment_quotes_borrower
    ON payment_partial_prepayment_quotes (borrower_id, created_at DESC, id DESC);

ALTER TABLE payment_repayments
    ADD COLUMN partial_prepayment_quote_id UUID,
    ADD CONSTRAINT fk_payment_repayments_partial_prepayment_quote
        FOREIGN KEY (partial_prepayment_quote_id)
        REFERENCES payment_partial_prepayment_quotes(quote_id) ON DELETE RESTRICT,
    ADD CONSTRAINT uq_payment_repayments_partial_prepayment_quote UNIQUE (partial_prepayment_quote_id);

ALTER TABLE payment_repayments DROP CONSTRAINT ck_payment_repayments_type;

ALTER TABLE payment_repayments
    ADD CONSTRAINT ck_payment_repayments_type CHECK (repayment_type IN (
        'SCHEDULED','OVERDUE_CURE','PARTIAL_PREPAYMENT','EARLY_SETTLEMENT'
    ));
